/**
 * Apple IIgs 遊戲庫
 * 生成時間: 2025/12/21 上午01:02:02
 * 遊戲數量: 122
 */

window.games = [
  {
    "id": "wozaday_4th_and_Inches_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "4th & Inches IIgs",
    "nameEn": "4th & Inches IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"4th & Inches\" is a 1988 sports game developed by Tony Manso & Sculptured Software and published by Accolade. It requires an Apple IIgs.",
    "developer": "Tony Manso & Sculptured Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Aaargh_1988_Arcadia_Software",
    "emu": "apple2gs",
    "file": "Aaargh_1988_Arcadia_Software.2mg",
    "name": "怪獸大暴走",
    "nameEn": "Aaargh!",
    "year": "1988",
    "type": "game",
    "desc": "這是一款快節奏的動作遊戲，玩家控制巨大怪獸在城市中大肆破壞。由 Synergistic Software 開發，Arcadia Software 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Synergistic Software",
    "publisher": "Arcadia Software",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "a2gs_Airball_1989_MicroDeal",
    "emu": "apple2gs",
    "file": "Airball_1989_MicroDeal.2mg",
    "name": "氣球歷險",
    "nameEn": "Airball",
    "year": "1989",
    "type": "game",
    "desc": "這是一款快節奏的動作遊戲，玩家控制一個氣球在複雜的迷宮中冒險。遊戲以其獨特的物理引擎和挑戰性的關卡設計而著稱。由 Jason Harper 開發，MicroDeal 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Jason Harper",
    "publisher": "MicroDeal",
    "screenshot": "https://archive.org/download/wozaday_Airball_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Alien_Mind",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Alien Mind",
    "nameEn": "Alien Mind",
    "year": "1988",
    "type": "game",
    "desc": "\"Alien Mind\" is a 1988 action-adventure game developed by Rob Karr & Matt Crysdale and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Rob Karr & Matt Crysdale",
    "publisher": "PBI Software",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Ancient_Glory_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Ancient Glory IIgs",
    "nameEn": "Ancient Glory IIgs",
    "year": "1993",
    "type": "game",
    "desc": "\"Ancient Glory\" is a 1993 action game developed by Logical Design Works, Westwood Associates and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Logical Design Works, Westwood Associates",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "e2gs_0487_Ancient_Land_of_Ys_Disk_1",
    "emu": "apple2gs",
    "file": "0487_Ancient_Land_of_Ys_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0488_Ancient_Land_of_Ys_Disk_2/0488_Ancient_Land_of_Ys_Disk_2.po",
    "name": "伊蘇古國",
    "nameEn": "Ancient Land of Ys",
    "year": "1989",
    "type": "game",
    "desc": "這是一款動作角色扮演遊戲，結合了快節奏的戰鬥和角色成長要素。經典的日式 RPG 作品，以其優美的音樂和引人入勝的故事情節而聞名。由 Designer Software 開發，Kyodai 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Designer Software",
    "publisher": "Kyodai",
    "screenshot": "https://www.video-games-museum.com/en/screenshots/Apple%20II%20GS/1/55909-title-Ancient-Land-of-Ys.jpg"
  },
  {
    "id": "wozaday_Arkanoid_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Arkanoid II: Revenge of Doh IIgs",
    "nameEn": "Arkanoid II: Revenge of Doh IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Arkanoid II: Revenge of Doh\" is a 1989 action game developed by Ryan Ridges & John Lund and published by Taito America. It requires an Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_As_the_Link_Turns_1988_Rogue_Systems_SW",
    "emu": "apple2gs",
    "file": "As_the_Link_Turns_1988_Rogue_Systems_SW.2mg",
    "name": "As the Link Turns",
    "nameEn": "As the Link Turns",
    "year": "1988",
    "type": "game",
    "desc": "Apple IIgs: As the Link Turns (1988)(Rogue Systems)(SW) 由 Parik Rao & Scott Pease (Rogue Systems) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Parik Rao & Scott Pease (Rogue Systems)",
    "publisher": "",
    "screenshot": "https://cdn.mobygames.com/screenshots/16854153-as-the-link-turns-operation-bug-apple-iigs-shooting-creatures.png"
  },
  {
    "id": "wozaday_Balance_of_Power_1990_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Balance of Power: The 1990 Edition IIgs",
    "nameEn": "Balance of Power: The 1990 Edition IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Balance of Power: The 1990 Edition\" is a 1989 simulation game developed by Chris Crawford and published by Mindscape. It requires an Apple IIgs.",
    "developer": "Chris Crawford",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Battle_Chess_1989_Interplay",
    "emu": "apple2gs",
    "file": "Battle_Chess_1989_Interplay.2mg",
    "name": "戰鬥西洋棋",
    "nameEn": "Battle Chess IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Battle Chess\" is a 1989 board game developed by Jim Sproul, Todd J. Camasta, Bruce Schlickbernd, Kurt Heiden, Bill (Weez) Dugan, Thomas R. Decker, Troy P. Worrell, Michael Quarles, Rebecca Heineman, and Alan Pavlish, and distributed by Interplay. It requires a 512K Apple IIgs. Battle Chess manual contains the information you need for the copy protection questions 這是一款棋類遊戲，電子化的傳統棋盤遊戲。 由 Rebecca Heineman 開發，Interplay Productions 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Beyond_Zork_1988_Infocom",
    "emu": "apple2gs",
    "file": "Beyond_Zork_1988_Infocom.2mg",
    "name": "Beyond Zork",
    "nameEn": "Beyond Zork",
    "year": "1988",
    "type": "game",
    "desc": "\"Beyond Zork: The Coconut of Quendor\" is a 1987 adventure game developed by Brian Moriarty and distributed by Infocom. This is revision 57 / 871221. It requires a 512K Apple IIgs ROM 00 or ROM 01. 由 Brian Moriarty 開發，Infocom 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Brian Moriarty",
    "publisher": "Infocom",
    "screenshot": "https://upload.wikimedia.org/wikipedia/en/0/0a/Beyond_Zork_game_box_cover.jpg"
  },
  {
    "id": "wozaday_Blackjack_Academy_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Blackjack Academy IIgs",
    "nameEn": "Blackjack Academy IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Blackjack Academy\" is a 1988 cards game developed by Westwood and published by Micro Illusions. It requires an Apple IIgs.",
    "developer": "Westwood",
    "publisher": "Micro Illusions",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Blockout_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Block Out IIgs",
    "nameEn": "Block Out IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Block Out\" is a 1989 puzzle game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Bridge_6_0_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Bridge 6.0 IIgs",
    "nameEn": "Bridge 6.0 IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Bridge 6.0\" is a 1989 cards game developed by Arthur Walsh & Roger Harnish and published by Artworx. It requires an Apple IIgs.",
    "developer": "Arthur Walsh & Roger Harnish",
    "publisher": "Artworx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Bubble_Ghost_1988_Accolade",
    "emu": "apple2gs",
    "file": "Bubble_Ghost_1988_Accolade.2mg",
    "name": "Bubble Ghost IIgs",
    "nameEn": "Bubble Ghost IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Bubble Ghost\" is a 1988 action game developed by Infogrames and distributed by Accolade. It requires a 512K Apple IIgs. 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 ERE Informatique 開發，Accolade 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "ERE Informatique",
    "publisher": "Accolade",
    "screenshot": "https://archive.org/download/wozaday_Bubble_Ghost_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_California_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "California Games IIgs",
    "nameEn": "California Games IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"California Games\" is a 1988 sports game developed by Designer Software (Jimmy Huey) and published by Epyx. It requires an Apple IIgs.",
    "developer": "Designer Software (Jimmy Huey)",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Captain_Blood_1989_Mindscape",
    "emu": "apple2gs",
    "file": "Captain_Blood_1989_Mindscape.2mg",
    "name": "Captain Blood IIgs",
    "nameEn": "Captain Blood IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Captain Blood\" is a 1989 simulation game developed by Philippe Ulrich, Didier Bouchon, Jean-Michel Jarre, Alexis Martial, and Michael Rho, and distributed by Mindscape. It requires a 512K Apple IIgs. 由 ERE Informatique (Alexis Martial & Jean-Michel Jarre) 開發，Mindscape 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",    "developer": "ERE Informatique (Alexis Martial & Jean-Michel Jarre)",
    "publisher": "Mindscape",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Carte_Primus_1989_Manthey_d_SW",
    "emu": "apple2gs",
    "file": "Carte_Primus_1989_Manthey_d_SW.2mg",
    "name": "Carte Primus",
    "nameEn": "Carte Primus",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Carte Primus (1989)(Manthey, David)(SW) 由 David Manthey 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "David Manthey",
    "publisher": "",
    "screenshot": "https://images.igdb.com/igdb/image/upload/t_720p/scdrts.jpg"
  },
  {
    "id": "wozaday_Cavern_Cobra_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Cavern Cobra IIgs",
    "nameEn": "Cavern Cobra IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Cavern Cobra\" is a 1987 shoot 'em up game developed by Greg Hale and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Greg Hale",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Club_Backgammon_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Club Backgammon IIgs",
    "nameEn": "Club Backgammon IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Club Backgammon\" is a 1988 board game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Cogito_1992_Brutal_Deluxe_FW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Cogito",
    "nameEn": "Cogito",
    "year": "1993",
    "type": "game",
    "desc": "Apple IIgs: Cogito (1992)(Brutal Deluxe)(FW) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Antoine Vignau & Olivier Zardini (Brutal Deluxe) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Antoine Vignau & Olivier Zardini (Brutal Deluxe)",
    "publisher": "",
    "file2": "Cogito_1992_Brutal_Deluxe_FW.2mg",
    "screenshot": "https://www.brutaldeluxe.fr/images/coglog12.gif"
  },
  {
    "id": "wozaday_Columns_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Columns GS",
    "nameEn": "Columns GS",
    "year": "1991",
    "type": "game",
    "desc": "\"Columns\" is a 1991 puzzle game developed by Kenrick Mock (Sound Barrier Systems) and published by . It requires an Apple IIgs.",
    "developer": "Kenrick Mock (Sound Barrier Systems)",
    "publisher": "",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Cribbage_Gin_King_1990_The_Software_Toolworks",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Gin King / Cribbage King IIgs",
    "nameEn": "Gin King / Cribbage King IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Gin King / Cribbage King\" is a 1989 board game developed by Mark Manyen, Don Laabs, David M. Linnehan, and Elizabeth Scafati, and distributed by The Software Toolworks. It requires a 1MB Apple IIgs. 由 Mark Manyen 開發，Software Toolworks 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Mark Manyen",
    "publisher": "Software Toolworks",
    "file2": "Cribbage__Gin_King_1990_The_Software_Toolworks.2mg",
    "screenshot": "https://archive.org/download/wozaday_Gin_King_Cribbage_King_IIgs/00playable_screenshot.png"
  },
  {
    "id": "a2gs_Crystal_Quest_1989_Cassidy_Greene",
    "emu": "apple2gs",
    "file": "Crystal_Quest_1989_Cassidy__Greene.2mg",
    "name": "水晶任務",
    "nameEn": "Crystal Quest IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Crystal Quest\" is a 1989 action game developed by Patrick Buckland, Rebecca Heineman, Mike 'Jed' Patrick, and Scott Everts, and distributed by Cassidy & Greene. It requires a 512K Apple IIgs. 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 Rebecca Heineman 開發，Cassidy & Greene 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Rebecca Heineman",
    "publisher": "Cassidy & Greene",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Dark_Castle_1989_09_22_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dark Castle 1989-09-22 IIgs",
    "nameEn": "Dark Castle 1989-09-22 IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Dark Castle\" is a 1989 action game developed by Lane Roath and published by Three Sixty. It requires an Apple IIgs.",
    "developer": "Lane Roath",
    "publisher": "Three Sixty",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Deja_Vu_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Déjà Vu II: Lost in Las Vegas IIgs",
    "nameEn": "Déjà Vu II: Lost in Las Vegas IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Deja Vu II: Lost in Las Vegas\" is a 1989 adventure game developed by ICOM Simulations and published by Mindscape. It requires an Apple IIgs.",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Destroyer_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Destroyer IIgs",
    "nameEn": "Destroyer IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Destroyer\" is a 1987 simulation game developed by Michael Kosaka & Chuck Sommerville and published by Epyx. It requires an Apple IIgs.",
    "developer": "Michael Kosaka & Chuck Sommerville",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Downhill_Challenge_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Downhill Challenge IIgs",
    "nameEn": "Downhill Challenge IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Downhill Challenge\" is a 1989 sports game developed by Microids and published by Broderbund. It requires an Apple IIgs.",
    "developer": "Microids",
    "publisher": "Broderbund",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Dragon_Wars_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dragon Wars IIgs",
    "nameEn": "Dragon Wars IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Dragon Wars\" is a 1990 rpg game developed by Rebecca Heineman and published by Interplay Productions. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Dream_Zone_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dream Zone IIgs",
    "nameEn": "Dream Zone IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Dream Zone\" is a 1988 adventure game developed by Naughty Dog (Andy Gavin & Jason Rubin) and published by Baudville. It requires an Apple IIgs.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Baudville",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Dueltris_1992_DreamWorld_FW_a_non_boot",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "DuelTris",
    "nameEn": "DuelTris",
    "year": "1992",
    "type": "game",
    "desc": "Apple IIgs: Dueltris (1992)(DreamWorld)(FW)[a][non boot] 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Steven Chiang, Dave Seah & James Brookes 開發，DreamWorld 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Steven Chiang, Dave Seah & James Brookes",
    "publisher": "DreamWorld",
    "file2": "Dueltris_1992_DreamWorld_FW_a_non_boot.2mg",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "a2gs_Dungeon_Master_1989_FTL",
    "emu": "apple2gs",
    "file": "Dungeon_Master_1989_FTL.2mg",
    "name": "地下城主",
    "nameEn": "Dungeon Master",
    "year": "1989",
    "type": "game",
    "desc": "這是一款革命性的即時角色扮演遊戲，採用第一人稱視角和即時戰鬥系統。玩家需要在地下城中探索、戰鬥並解決各種謎題。由 Don Jordan 開發，FTL 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Don Jordan",
    "publisher": "FTL",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Fast_Break_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Fast Break IIgs",
    "nameEn": "Fast Break IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Fast Break\" is a 1989 sports game developed by Greg Hospelhorn & George Wong and published by Accolade. It requires an Apple IIgs.",
    "developer": "Greg Hospelhorn & George Wong",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Final_Assault_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Final Assault IIgs",
    "nameEn": "Final Assault IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Final Assault\" is a 1988 simulation game developed by Infogrames and published by Epyx. It requires an Apple IIgs.",
    "developer": "Infogrames",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Firepower_1989_MicroIllusions",
    "emu": "apple2gs",
    "file": "Firepower_1989_MicroIllusions.2mg",
    "name": "Firepower",
    "nameEn": "Firepower",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Firepower (1989)(MicroIllusions) 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 Stephen Lepisto 開發，MicroIllusions 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Stephen Lepisto",
    "publisher": "MicroIllusions",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Full_Metal_Planete_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Full Metal Planete IIgs",
    "nameEn": "Full Metal Planete IIgs",
    "year": "1993",
    "type": "game",
    "desc": "\"Full Metal Planete\" is a 1993 turn-based strategy game developed by Brainstorm Software (Francois Uhrich & Nicolas Bergeret) and published by Infogrames. It requires an Apple IIgs.",
    "developer": "Brainstorm Software (Francois Uhrich & Nicolas Bergeret)",
    "publisher": "Infogrames",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_GATE_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "GATE IIgs",
    "nameEn": "GATE IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"GATE\" is a 1991 action-adventure game developed by Bright Software (Joerg Kienzle, Yann Le Tensorer & Henrik Gudat) and published by Toolbox & Seven Hills. It requires an Apple IIgs.",
    "developer": "Bright Software (Joerg Kienzle, Yann Le Tensorer & Henrik Gudat)",
    "publisher": "Toolbox & Seven Hills",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Gauntlet_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gauntlet IIgs",
    "nameEn": "Gauntlet IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Gauntlet\" is a 1988 action game developed by Atari Games and published by Mindscape. It requires an Apple IIgs.",
    "developer": "Atari Games",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_GBA_Championship_Basketball_Two-On-Two_1987_Gamestar_Activision",
    "emu": "apple2gs",
    "file": "GBA_Championship_Basketball_Two-On-Two_1987_Gamestar_Activision.2mg",
    "name": "GBA Championship Basketball: Two on Two",
    "nameEn": "GBA Championship Basketball: Two on Two",
    "year": "1987",
    "type": "game",
    "desc": "Apple IIgs: GBA Championship Basketball Two On Two (1987)(Gamestar Activision) 這是一款運動遊戲，模擬各種體育競技項目。 由 Gamestar (Paul Terry & Jack Thornton) 開發，Activision 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Gamestar (Paul Terry & Jack Thornton)",
    "publisher": "Activision",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Gnarly_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gnarly Golf IIgs",
    "nameEn": "Gnarly Golf IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Gnarly Golf\" is a 1989 sports game developed by Visual Concepts (Jim Coliz Jnr & Darren Bartlett) and published by Britannica / Fanfare. It requires an Apple IIgs.",
    "developer": "Visual Concepts (Jim Coliz Jnr & Darren Bartlett)",
    "publisher": "Britannica / Fanfare",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Grand_Prix_Circuit_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Grand Prix Circuit IIgs",
    "nameEn": "Grand Prix Circuit IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Grand Prix Circuit\" is a 1989 racing game developed by Distinctive Software and published by Accolade. It requires an Apple IIgs.",
    "developer": "Distinctive Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Halls_of_Montezuma_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Halls of Montezuma IIgs",
    "nameEn": "Halls of Montezuma IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Halls of Montezuma\" is a 1990 turn-based strategy game developed by Roger Keating & Ian Trout and published by Strategic Studies Group. It requires an Apple IIgs.",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Hardball_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Hardball! IIgs",
    "nameEn": "Hardball! IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"HardBall!\" is a 1987 sports game developed by Distinctive Software (Dan Thompson) and published by Accolade. It requires an Apple IIgs.",
    "developer": "Distinctive Software (Dan Thompson)",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Hostage_1990_Mindscape",
    "emu": "apple2gs",
    "file": "Hostage_1990_Mindscape.2mg",
    "name": "Hostage",
    "nameEn": "Hostage",
    "year": "1990",
    "type": "game",
    "desc": "\"Hostage: Rescue Mission\" is a 1990 simulation game developed by Infogrames and distributed by Mindscape. It requires a 512K Apple IIgs. 由 Infogrames 開發，Mindscape 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Infogrames",
    "publisher": "Mindscape",
    "screenshot": "https://archive.org/download/wozaday_Hostage_Rescue_Mission_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Hover_Blade_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "https://archive.org/download/wozaday_Hover_Blade_IIgs/Hover%20Blade%20IIgs%20%28woz-a-day%20collection%29.zip/Hover%20Blade%20IIgs%20%28woz-a-day%20collection%29%2FHover%20Blade%20IIgs%20-%20Disk%202.woz",
    "name": "Hover Blade IIgs",
    "nameEn": "Hover Blade IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"Hover Blade\" is a 1991 action game developed by Shiraz Akmal & Eric Boden and published by MCX. It requires an Apple IIgs.",
    "developer": "Shiraz Akmal & Eric Boden",
    "publisher": "MCX",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Impossible_Mission_II_1989_Epyx",
    "emu": "apple2gs",
    "file": "Impossible_Mission_II_1989_Epyx.2mg",
    "name": "不可能的任務 2",
    "nameEn": "Impossible Mission 2",
    "year": "1989",
    "type": "game",
    "desc": "這是一款動作冒險遊戲，玩家扮演特工潛入敵人基地執行任務。遊戲結合了平台跳躍、解謎和探索元素。由 Novotrade 開發，Epyx 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Novotrade",
    "publisher": "Epyx",
    "screenshot": "https://archive.org/download/wozaday_Impossible_Mission_II_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Invisible_Bugs_800K",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Invisible Bugs",
    "nameEn": "Invisible Bugs",
    "year": "2021",
    "type": "game",
    "desc": "\"BuGS\" is a 2021 shoot 'em up game developed by Jeremy Rand and published by . It requires an Apple IIgs.",
    "developer": "Jeremy Rand",
    "publisher": "",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Kaleidokubes_1989_Artworx",
    "emu": "apple2gs",
    "file": "Kaleidokubes_1989_Artworx.2mg",
    "name": "Kaleidokubes",
    "nameEn": "Kaleidokubes",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Kaleidokubes (1989)(Artworx) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Bob & Betsy Couch 開發，Artworx 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Bob & Betsy Couch",
    "publisher": "Artworx",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Keef_the_Thief_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0907_Keef_the_Thief_Disk_1/0907_Keef_the_Thief_Disk_1.po",
	"file2": "https://archive.org/download/e2gs_0908_Keef_the_Thief_Disk_2/0908_Keef_the_Thief_Disk_2.po",
    "name": "盜賊基夫",
    "nameEn": "Keef the Thief",
    "year": "1989",
    "type": "game",
    "desc": "這是一款幽默風趣的角色扮演遊戲，玩家扮演一名盜賊在奇幻世界中冒險。遊戲以其詼諧的對話和獨特的角色設定而著稱。由 Naughty Dog (Andy Gavin & Jason Rubin) 開發，Electronic Arts 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Leisure_Suit_Larry_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0283_Leisure_Suit_Larry_Disk_1/0283_Leisure_Suit_Larry_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0284_Leisure_Suit_Larry_Disk_2/0284_Leisure_Suit_Larry_Disk_2.po",
    "name": "Leisure Suit Larry in the Land of the Lounge Lizards IIgs",
    "nameEn": "Leisure Suit Larry in the Land of the Lounge Lizards IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Leisure Suit Larry in the Land of the Lounge Lizards\" is a 1987 adventure game developed by Al Lowe and published by Sierra. It requires an Apple IIgs.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Life_and_Death_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Life and Death IIgs",
    "nameEn": "Life and Death IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Life & Death\" is a 1989 simulation game developed by Mark Manyen & Jacob P. Smith and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "Mark Manyen & Jacob P. Smith",
    "publisher": "Software Toolworks",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Lost_Tribe_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Lost Tribe, The",
    "nameEn": "Lost Tribe, The",
    "year": "1992",
    "type": "game",
    "desc": "\"The Lost Tribe\" is a 1992 educational game developed by Frank Andrews, Steve Vance, Todd Harris, Susan Wiltse, James R. McCarthy, and Mark Moore, and distributed by Lawrence Productions. This is version 1.0. It requires an Apple IIgs with at least 1MB RAM (2MB recommended). 由 Steve Vance, Frank Andrews & Todd Harris 開發，Lawrence Productions 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Steve Vance, Frank Andrews & Todd Harris",
    "publisher": "Lawrence Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Mad_Match_1989_Baudville",
    "emu": "apple2gs",
    "file": "Mad_Match_1989_Baudville.2mg",
    "name": "Mad Match",
    "nameEn": "Mad Match",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Mad Match (1989)(Baudville) 由 Paul Gauthier 開發，Baudville 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Paul Gauthier",
    "publisher": "Baudville",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Mancala_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Mancala_1988_California_Dreams.2mg",
    "name": "Mancala IIgs",
    "nameEn": "Mancala IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mancala\" is a 1988 board game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "https://archive.org/download/wozaday_Mancala_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Marble_Madness_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Marble Madness IIgs",
    "nameEn": "Marble Madness IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Marble Madness\" is a 1988 action game developed by Will Harvey and published by Electronic Arts. It requires an Apple IIgs.",
    "developer": "Will Harvey",
    "publisher": "Electronic Arts",
    "screenshot": "https://archive.org/download/wozaday_Marble_Madness/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mazer_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mazer II IIgs",
    "nameEn": "Mazer II IIgs",
    "year": "1992",
    "type": "game",
    "desc": "\"Mazer II\" is a 1992 action rpg game developed by Farfetch Software and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Farfetch Software",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mini_Putt_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Mini_Putt_The_Ultimate_Challenge_1988_Accolade/Mini_Putt_The_Ultimate_Challenge_1988_Accolade.2mg",
    "name": "Mini-Putt IIgs",
    "nameEn": "Mini-Putt IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mini-Putt\" is a 1988 sports game developed by Ross Salas & Tanager Software Productions and published by Accolade. It requires an Apple IIgs.",
    "developer": "Ross Salas & Tanager Software Productions",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mixed_Up_Mother_Goose_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mixed-Up Mother Goose IIgs",
    "nameEn": "Mixed-Up Mother Goose IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mixed Up Mother Goose\" is a 1988 adventure game developed by Roberta Williams and published by Sierra. It requires an Apple IIgs.",
    "developer": "Roberta Williams",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Monte_Carlo_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Monte_Carlo_1988_PBI_Software/Monte_Carlo_1988_PBI_Software.2mg",
    "name": "Monte Carlo IIgs",
    "nameEn": "Monte Carlo IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Monte Carlo\" is a 1987 gambling game developed by Richard Seaborne & Jeff Lefferts and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Neuromancer_1989_Interplay",
    "emu": "apple2gs",
    "file": "Neuromancer_1989_Interplay.2mg",
    "name": "Neuromancer IIgs",
    "nameEn": "Neuromancer IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Neuromancer\" is a 1989 adventure game developed by Rebecca Heineman and published by Interplay Productions. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Omega_1990_Origin",
    "emu": "apple2gs",
    "file": "Omega_1990_Origin.2mg",
    "name": "Omega IIgs",
    "nameEn": "Omega IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Omega\" is a 1990 simulation game developed by Micro Magic and published by Origin. It requires an Apple IIgs.",
    "developer": "Micro Magic",
    "publisher": "Origin",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Panzer_Battles_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Panzer Battles IIgs",
    "nameEn": "Panzer Battles IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"Panzer Battles\" is a 1991 turn-based strategy game developed by Roger Keating, Danny Stevens & Ian Trout and published by Strategic Studies Group. It requires an Apple IIgs.",
    "developer": "Roger Keating, Danny Stevens & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Paperboy_1988_Mindscape",
    "emu": "apple2gs",
    "file": "Paperboy_1988_Mindscape.2mg",
    "name": "送報生",
    "nameEn": "Paperboy",
    "year": "1988",
    "type": "game",
    "desc": "Apple IIgs: Paperboy (1988)(Mindscape) 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 Atari Games 開發，Mindscape 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Atari Games",
    "publisher": "Mindscape",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Pipe_Dream_1990_Lucasfilm_Games",
    "emu": "apple2gs",
    "file": "Pipe_Dream_1990_Lucasfilm_Games.2mg",
    "name": "Pipe Dream IIgs",
    "nameEn": "Pipe Dream IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Pipe Dream\" is a 1990 puzzle game developed by Visual Concepts and published by Lucasfilm Games. It requires an Apple IIgs.",
    "developer": "Visual Concepts",
    "publisher": "Lucasfilm Games",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Pirates_1988_Microprose",
    "emu": "apple2gs",
    "file": "Pirates_1988_Microprose.2mg",
    "name": "海盜！",
    "nameEn": "Pirates!",
    "year": "1988",
    "type": "game",
    "desc": "這是一款動作策略遊戲，玩家扮演加勒比海的海盜船長，可以進行貿易、戰鬥、探索和掠奪。Sid Meier 的經典作品之一，結合了多種遊戲元素。由 Ed Magnin 開發，Microprose 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Ed Magnin",
    "publisher": "Microprose",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_Police_Quest_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0334_Police_Quest_DIsk_1/0334_Police_Quest_DIsk_1.po",
    "file2": "https://archive.org/download/e2gs_0335_Police_Quest_Disk_2/0335_Police_Quest_Disk_2.po",
    "name": "Police Quest IIgs",
    "nameEn": "Police Quest IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Police Quest\" is a 1987 adventure game developed by Jim Walls and published by Sierra. It requires an Apple IIgs.",
    "developer": "Jim Walls",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Qix_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Qix_1990_Taito_US/Qix_1990_Taito_US.2mg",
    "name": "Qix IIgs",
    "nameEn": "Qix IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Qix\" is a 1990 action game developed by Ryan Ridges & John Lund and published by Taito America. It requires an Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Quest_for_the_Hoard_1991_Pegasoft_SW",
    "emu": "apple2gs",
    "file": "Quest_for_the_Hoard_1991_Pegasoft_SW.2mg",
    "name": "Quest for the Hoard",
    "nameEn": "Quest for the Hoard",
    "year": "1991",
    "type": "game",
    "desc": "Apple IIgs: Quest for the Hoard (1991)(Pegasoft)(SW) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Ken Burtch (Pegasoft) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Ken Burtch (Pegasoft)",
    "publisher": "",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "a2gs_Questron_II_1988_SSI",
    "emu": "apple2gs",
    "file": "Questron_II_1988_SSI.2mg",
    "name": "Questron II",
    "nameEn": "Questron II",
    "year": "1988",
    "type": "game",
    "desc": "\"Questron II\" is a 1988 roleplaying game developed by Westwood Associates and distributed by Strategic Simulations, Inc. This is version 1.1. It requires a 512K Apple IIgs. 這是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。 由 Westwood 開發，Strategic Simulations 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Westwood",
    "publisher": "Strategic Simulations",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Rastan",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Rastan",
    "nameEn": "Rastan",
    "year": "1990",
    "type": "game",
    "desc": "\"Rastan\" is a 1990 action game developed by John Brooks and distributed by Taito. It requires a 1MB Apple IIgs. (Music requires 1.25MB.) 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 John Brooks 開發，Taito America 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "John Brooks",
    "publisher": "Taito America",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Reach_For_The_Stars_1988_SSG",
    "emu": "apple2gs",
    "file": "Reach_For_The_Stars_1988_SSG.2mg",
    "name": "Reach for the Stars",
    "nameEn": "Reach for the Stars",
    "year": "1988",
    "type": "game",
    "desc": "\"Reach for the Stars\" is a 1988 simulation game developed by Roger Keating, Ian Trout, and Allan Bell, and distributed by Strategic Studies Group. It requires a 512K Apple IIgs. 由 Roger Keating & Ian Trout 開發，Strategic Studies Group 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Roadwar_2000_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Roadwar_2000_1987_SSI/Roadwar_2000_1987_SSI.2mg",
    "name": "Roadwar 2000",
    "nameEn": "Roadwar 2000",
    "year": "1987",
    "type": "game",
    "desc": "\"Roadwar 2000\" is a 1987 simulation game developed by Westwood Associates and distributed by Strategic Simulations, Inc. It requires a 512K Apple IIgs. 由 Westwood 開發，Strategic Simulations 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Westwood",
    "publisher": "Strategic Simulations",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Rocket_Ranger_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0729_Rocket_Ranger_Disk_1/0729_Rocket_Ranger_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0730_Rocket_Ranger_Disk_2/0730_Rocket_Ranger_Disk_2.po",
    "name": "火箭騎兵",
    "nameEn": "Rocket Ranger",
    "year": "1989",
    "type": "game",
    "desc": "這是一款動作策略遊戲，設定在二戰時期的另類歷史中。玩家扮演配備火箭背包的特工對抗納粹。遊戲結合了動作、策略和冒險元素。由 Ed Magnin 開發，Cinemaware 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Ed Magnin",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Sea_Strike_1987_PBI_Software",
    "emu": "apple2gs",
    "file": "Sea_Strike_1987_PBI_Software.2mg",
    "name": "Sea Strike",
    "nameEn": "Sea Strike",
    "year": "1987",
    "type": "game",
    "desc": "\"Sea Strike\" is a 1987 action game developed by Richard L. Seaborne, Jeff A. Lefferts, and Mei-Ying Dell'Aquila, and distributed by PBI Software. It requires a 512K Apple IIgs. 由 Richard Seaborne & Jeff Lefferts 開發，PBI Software 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Sensei_1991_Miami_Software_FW",
    "emu": "apple2gs",
    "file": "Sensei_1991_Miami_Software_FW.2mg",
    "name": "Sensei",
    "nameEn": "Sensei",
    "year": "1991",
    "type": "game",
    "desc": "Apple IIgs: Sensei (1991)(Miami Software)(FW) 由 Phil Rivipellio, Walt Scapela & Neil Pulcadesso (Miami Software) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Phil Rivipellio, Walt Scapela & Neil Pulcadesso (Miami Software)",
    "publisher": "",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Serve_and_Volley_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0750_Serve_Volley/0750_Serve__Volley.po",
    "name": "Serve & Volley",
    "nameEn": "Serve & Volley",
    "year": "1988",
    "type": "game",
    "desc": "\"Serve & Volley\" is a 1988 sports game developed by Rick Banks, Paul Butler, Ken Shimizu, Danny Chin, Paul Battersby, Jeffrey J. Sigler, Grant Campbell, and Jay Stevens, and distributed by Accolade. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 Jeffrey Sigler 開發，Accolade 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Jeffrey Sigler",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Shadowgate_1988_Mindscape",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "file2": "Shadowgate_1988_Mindscape.2mg",
    "name": "影之門",
    "nameEn": "Shadowgate",
    "year": "1988",
    "type": "game",
    "desc": "\"Shadowgate\" is a 1988 adventure game developed by Fred Allen, David Marsh, Karl Roelofs, Todd Squires, Steven Hays, Terry Schulenburg, Darin Adler, Jay Zipnick, Waldemar Horwat, Tod Zipnick, and David Feldman, and distributed by ICOM Simulations. It requires a 768K Apple IIgs. 這是一款冒險遊戲，玩家需要探索世界、解決謎題並推進劇情。 由 ICOM Simulations 開發，Mindscape 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "screenshot": "https://archive.org/download/wozaday_Shadowgate_IIgs/00playable_screenshot.png"
  },
  {
    "id": "wozaday_Shanghai_II_Dragons_Eye_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "上海2",
    "nameEn": "Shanghai II",
    "year": "1987",
    "type": "game",
    "desc": "\"Shanghai II: Dragon's Eye\" is a 1993 board game developed by Brodie Lockard, Don Harlow, John Wrenholt, and Steve Luellman, and distributed by Big Red Computer Club. It requires a 1MB Apple IIgs ROM 01 or later. 這是一款棋類遊戲，電子化的傳統棋盤遊戲。 由 Manley & Associates (Brodie Lockard & Ivan Manley) 開發，Activision 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Manley & Associates (Brodie Lockard & Ivan Manley)",
    "publisher": "Activision",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Silent_Service_1987_Microprose",
    "emu": "apple2gs",
    "file": "Silent_Service_1987_Microprose.2mg",
    "name": "Silent Service",
    "nameEn": "Silent Service",
    "year": "1987",
    "type": "game",
    "desc": "\"Silent Service\" is a 1987 simulation game developed by Sid Meier, Ed Magnin, Jim Synoski, Michael Haire, Michele Mahan, Silas Warner, Al Roireau, Larry Martin, and Edward Bever, and distributed by Microprose. It requires a 256K Apple IIgs. 這是一款模擬遊戲，讓玩家體驗各種真實或虛構的情境。 由 Ed Magnin 開發，Microprose 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Ed Magnin",
    "publisher": "Microprose",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Silpheed_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0644_Silpheed_Disk_1/0644_Silpheed_Disk_1.po",
	"file2": "https://archive.org/download/e2gs_0645_Silpheed_Disk_2/0645_Silpheed_Disk_2.po",
    "name": "銀河戰機",
    "nameEn": "Silpheed",
    "year": "1989",
    "type": "game",
    "desc": "這是一款垂直卷軸射擊遊戲，玩家駕駛先進的戰鬥機對抗外星入侵者。遊戲以其出色的 3D 圖形效果和激烈的戰鬥而著稱。由 Game Arts 開發，Sierra 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Game Arts",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Sinbad_and_the_Throne_of_the_Falcon",
    "emu": "apple2gs",
    "file": "00playable.woz",
	"file2": "00playable2.woz",
    "name": "辛巴達與獵鷹王座",
    "nameEn": "Sinbad and the Throne of the Falcon",
    "year": "1990",
    "type": "game",
    "desc": "這是一款動作冒險遊戲，基於阿拉伯神話中的辛巴達故事。玩家扮演辛巴達在阿拉伯世界中冒險，尋找傳說中的寶藏。由 Jim Simmons & Andrew Caldwell 開發，Cinemaware 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 後期的優秀作品。",
    "developer": "Jim Simmons & Andrew Caldwell",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Skate_or_Die_v10_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "滑板生死戰",
    "nameEn": "Skate or Die!",
    "year": "1988",
    "type": "game",
    "desc": "這是一款運動遊戲，模擬滑板運動的各種項目。遊戲包含多種不同的滑板挑戰，從半管到街頭滑板。由 David Bunch, Michael Kosaka & Michelle Shelfer 開發，Electronic Arts 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "David Bunch, Michael Kosaka & Michelle Shelfer",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Solarian_1992_Coloreez_SW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Solarian",
    "nameEn": "Solarian",
    "year": "1992",
    "type": "game",
    "desc": "Apple IIgs: Solarian (1992)(Coloreez)(SW) 由 David Tolson 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "David Tolson",
    "publisher": "",
    "file2": "Solarian_1992_Coloreez_SW.2mg",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_Solitaire_and_Cribbage_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Solitaire & Cribbage",
    "nameEn": "Solitaire & Cribbage",
    "year": "1990",
    "type": "game",
    "desc": "\"Solitaire & Cribbage\" is a 1989 pair of games developed and distributed by Computrek. It requires an Apple IIgs with at least 256K RAM. Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "",
    "publisher": "Computrek Software",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Solitaire_Royale_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Solitaire Royale",
    "nameEn": "Solitaire Royale",
    "year": "1990",
    "type": "game",
    "desc": "\"Solitaire Royale\" is a 1989 card game developed by Jake Hoelter, Jody Sather, Ilan \"The Zipper\" Zipkin, and Brad Fregger, and distributed by Spectrum Holobyte. This is version 1.0. It requires a 512K Apple IIgs. 由 Jake Hoelter, Jody Sather & Brad Fregger 開發，Spectrum Holobyte 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Jake Hoelter, Jody Sather & Brad Fregger",
    "publisher": "Spectrum Holobyte",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Space_Ace_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Space Ace",
    "nameEn": "Space Ace",
    "year": "1990",
    "type": "game",
    "desc": "\"Space Ace\" is a 1990 action game developed by David Foster, Simon Douglas, Jorge Freitas, Hugh MacLeod, Murray Foster, Laurie Williams, Adam Wolk, Michael Griffith, Peter Bayes, David Dimatteo, Sue McComb, and Joanne Ashdown, and distributed by ReadySoft. It requires a 1MB Apple IIgs. 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 David Foster & Simon Douglas 開發，Ready Soft 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "David Foster & Simon Douglas",
    "publisher": "Ready Soft",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Space_Shark_1990_Toolbox",
    "emu": "apple2gs",
    "file": "Space_Shark_1990_Toolbox.2mg",
    "name": "Space Shark",
    "nameEn": "Space Shark",
    "year": "1990",
    "type": "game",
    "desc": "Apple IIgs: Space Shark (1990)(Toolbox) 由 Miami Software 開發，Toolbox 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Miami Software",
    "publisher": "Toolbox",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Star_Saga_One_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Star_Saga_One_Beyond_the_Boundary_1988_MasterPlay/Star_Saga_One_Beyond_the_Boundary_1988_MasterPlay.2mg",
    "name": "Star Saga One: Beyond the Boundary",
    "nameEn": "Star Saga One: Beyond the Boundary",
    "year": "1988",
    "type": "game",
    "desc": "\"Star Saga: One - Beyond The Boundary\" is a 1987 roleplaying game developed by Richard Dutton, Walter Freitag, Andrew C. Greenberg, and Michael Massimilla, and distributed by Masterplay Publishing Corporation. This is version 1.1. It requires a 512K Apple IIgs. 這是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。 由 Richard Dutton, Walter Freitag, Andrew Greenberg, Michael Massimilla 開發，Master Play 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Richard Dutton, Walter Freitag, Andrew Greenberg, Michael Massimilla",
    "publisher": "Master Play",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Star_Saga_Two_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Star_Saga_Two_The_Clathran_Menance_v1.0_1988_MasterPlay/Star_Saga_Two_The_Clathran_Menance_v1.0_1988_MasterPlay.2mg",
    "name": "Star Saga: Two - The Clathran Menace",
    "nameEn": "Star Saga: Two - The Clathran Menace",
    "year": "1988",
    "type": "game",
    "desc": "\"Star Saga: Two - The Clathran Menace\" is a 1988 roleplaying game developed by Richard Dutton, Walter Freitag, Andrew C. Greenberg, Sheila M. Greenberg, Michael Massimilla, and Gerald M. Seixas, and distributed by MasterPlay Publishing Corporation. It requires a 512K Apple IIgs. 這是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。 由 Richard Dutton, Walter Freitag, A. & S. Greenberg, Michael Massimilla, Gerald Seixas 開發，Master Play 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Richard Dutton, Walter Freitag, A. & S. Greenberg, Michael Massimilla, Gerald Seixas",
    "publisher": "Master Play",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Sub_Battle_Simulator_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Sub Battle Simulator",
    "nameEn": "Sub Battle Simulator",
    "year": "1987",
    "type": "game",
    "desc": "\"Sub Battle Simulator\" is a 1987 simulation game developed by Rob Brannon, Kelly Fergason, and Steve Snyder, and distributed by Epyx. It requires a 768K Apple IIgs. 這是一款模擬遊戲，讓玩家體驗各種真實或虛構的情境。 由 Rob Brannon & Kelly Fergason 開發，Epyx 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Rob Brannon & Kelly Fergason",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Superstar_Ice_Hockey_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Superstar Ice Hockey",
    "nameEn": "Superstar Ice Hockey",
    "year": "1988",
    "type": "game",
    "desc": "\"Superstar Ice Hockey\" is a 1988 sports game developed by Ed Ringler, Andrew Caldwell, Clayton Wishoff, Simon Ffinch, Ed Ringler Sr., and Chris Oke, and distributed by Mindscape. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 DesignStar Consultants (Andrew Caldwell) 開發，Mindscape 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "DesignStar Consultants (Andrew Caldwell)",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Tarot_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tarot",
    "nameEn": "Tarot",
    "year": "1990",
    "type": "game",
    "desc": "\"Tarot\" is a 1990 French language card game developed by François Uhrich and Jean-François Sauvage, and distributed by Toolbox. It requires a 1MB Apple IIgs ROM 01 or later. 由 François Uhrich & Jean-François Sauvage 開發，Toolbox 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "François Uhrich & Jean-François Sauvage",
    "publisher": "Toolbox",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Task_Force_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Task Force",
    "nameEn": "Task Force",
    "year": "1990",
    "type": "game",
    "desc": "\"Task Force\" is a 1990 action game developed by Scott L. Patterson, Matthew Crysdale, and Gregory A. Thomas, and distributed by Britannica Software. It requires a 1MB Apple IIgs. 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 Visual Concepts (Scott Patterson & Matt Crysdale) 開發，Britannica / Fanfare 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Visual Concepts (Scott Patterson & Matt Crysdale)",
    "publisher": "Britannica / Fanfare",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Tass_Times_in_Tonetown_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tass Times in Tonetown",
    "nameEn": "Tass Times in Tonetown",
    "year": "1986",
    "type": "game",
    "desc": "\"Tass Times in Tonetown\" is a 1986 adventure game developed by Rebecca Heineman, Todd Camasta, Russell Lieblich, Brian Fargo, and Steve Nielsen, and distributed by Activision. It requires a 256K Apple IIgs. 這是一款冒險遊戲，玩家需要探索世界、解決謎題並推進劇情。 由 Rebecca Heineman (Interplay Productions & Brainwave Creations) 開發，Activision 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Rebecca Heineman (Interplay Productions & Brainwave Creations)",
    "publisher": "Activision",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Tetris_1988_Spectrum_Holobyte",
    "emu": "apple2gs",
    "file": "Tetris_1988_Spectrum_Holobyte.2mg",
    "name": "俄羅斯方塊",
    "nameEn": "Tetris",
    "year": "1988",
    "type": "game",
    "desc": "\"Tetris\" is a 1988 action game developed by Roland Gustafsson, Sean B. Barger, Dan Geisler, Daniel L. Guerra, Jody Sather, Ed Bogas, Neil Cormia, Ty Roberts, and Gary Clayton, and distributed by Spectrum HoloByte. It requires a 512K Apple IIgs. 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Roland Gustafsson, Sean Barger & Dan Geisler 開發，Spectrum Holobyte 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Roland Gustafsson, Sean Barger & Dan Geisler",
    "publisher": "Spectrum Holobyte",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_The_Bards_Tale_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "冰城傳奇",
    "nameEn": "The Bard's Tale",
    "year": "1988",
    "type": "game",
    "desc": "這是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。由 Rebecca Heineman 開發，Electronic Arts 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Rebecca Heineman",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Black_Cauldron_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Black Cauldron IIgs",
    "nameEn": "The Black Cauldron IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Black Cauldron\" is a 1987 adventure game developed by Al Lowe and published by Sierra. It requires an Apple IIgs.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Hunt_for_Red_October_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Hunt for Red October IIgs",
    "nameEn": "The Hunt for Red October IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Hunt for Red October\" is a 1989 simulation game developed by John Brooks, Todd Daugherty & Alex Villagran and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "John Brooks, Todd Daugherty & Alex Villagran",
    "publisher": "Software Toolworks",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_King_of_Chicago_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The King of Chicago IIgs",
    "nameEn": "The King of Chicago IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"King of Chicago\" is a 1989 action/strategy game developed by Doug Sharp and published by Cinemaware. It requires an Apple IIgs.",
    "developer": "Doug Sharp",
    "publisher": "Cinemaware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Last_Ninja_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Last Ninja IIgs",
    "nameEn": "The Last Ninja IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Last Ninja, The\" is a 1988 action-adventure game developed by System 3 and published by Activision. It requires an Apple IIgs.",
    "developer": "System 3",
    "publisher": "Activision",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_The_Three_Stooges_1990_Cinemaware",
    "emu": "apple2gs",
    "file": "The_Three_Stooges_1990_Cinemaware.2mg",
    "name": "三個活寶",
    "nameEn": "The Three Stooges",
    "year": "1990",
    "type": "game",
    "desc": "這是一款動作冒險遊戲，基於經典的三個活寶喜劇系列。玩家控制三個角色進行各種滑稽的冒險。遊戲以其幽默的內容和多樣化的小遊戲而著稱。由 Ed Magnin 開發，Cinemaware 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 後期的優秀作品。",
    "developer": "Ed Magnin",
    "publisher": "Cinemaware",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_Thexder_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Thexder_1987_Sierra/Thexder_1987_Sierra.2mg",
    "name": "機甲戰士",
    "nameEn": "Thexder",
    "year": "1987",
    "type": "game",
    "desc": "這是一款橫向卷軸射擊遊戲，玩家控制可變形的機器人戰士。機器人可以在人形和戰鬥機形態之間切換，每種形態都有不同的能力。由 Game Arts 開發，Sierra 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Game Arts",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Third_Courier_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Third Courier, The",
    "nameEn": "Third Courier, The",
    "year": "1989",
    "type": "game",
    "desc": "\"The Third Courier\" is a 1989 adventure game developed by Carol Manley, Ivan Manley, Mike Branham, Robert Clardy, Chris Barker, Scott Wallin, Miik Nichols, Sheldon Safir, and Mark Wallace, and distributed by Accolade. It requires a 768K Apple IIgs ROM01 or later. 由 Manley & Associates 開發，Accolade 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Manley & Associates",
    "publisher": "Accolade",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Three_Stooges_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Three Stooges, The",
    "nameEn": "Three Stooges, The",
    "year": "1990",
    "type": "game",
    "desc": "\"The Three Stooges\" is a 1987 adventure game developed by John Cutter, Robert Jacob, Phyllis Jacob, Ed Magnin, Russell Truelove, Jim Simmons, and Patrick Cook, and distributed by Cinemaware. It requires an Apple IIgs ROM1 or later with 1.25 MB of RAM. 由 Ed Magnin 開發，Cinemaware 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Ed Magnin",
    "publisher": "Cinemaware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Tinies_The_1994_Brutal_Deluxe_FW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Tinies, The",
    "nameEn": "Tinies, The",
    "year": "1994",
    "type": "game",
    "desc": "Apple IIgs: Tinies, The (1994)(Brutal Deluxe)(FW) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Antoine Vignau & Olivier Zardini (Brutal Deluxe) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Antoine Vignau & Olivier Zardini (Brutal Deluxe)",
    "publisher": "",
    "file2": "Tinies_The_1994_Brutal_Deluxe_FW.2mg",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_Tomahawk_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tomahawk",
    "nameEn": "Tomahawk",
    "year": "1988",
    "type": "game",
    "desc": "\"Tomahawk\" is a 1987 simulation game ported to the Apple IIgs by John Brooks; sound effects by John Brooks, Thomas J. Clement, and Jerry Vincent; music by Thomas J. Clement; graphics by Bonita Long-Hemsath and John Brooks; disk routines by Robin Kar and John Brooks; based on an original game by D.K. Marshall; and distributed by Datasoft. It requires a 512K Apple IIgs. 由 John Brooks 開發，Datasoft 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "John Brooks",
    "publisher": "Datasoft",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Tower_of_Myraglen_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tower of Myraglen",
    "nameEn": "Tower of Myraglen",
    "year": "1987",
    "type": "game",
    "desc": "\"The Tower of Myraglen\" is a 1987 roleplaying game developed by Richard L. Seaborne and Jeff A. Lamberts, and distributed by PBI Software. It requires a 768K Apple IIgs. 由 Richard Seaborne & Jeff Lefferts 開發，PBI Software 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Transylvania_III_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Transylvania III",
    "nameEn": "Transylvania III",
    "year": "1990",
    "type": "game",
    "desc": "\"Transylvania III\" is a 1991 adventure game developed by Antonio Antiochia and Veronika Slintak, and distributed by Polarware. It runs on any Apple IIgs. 這是一款冒險遊戲，玩家需要探索世界、解決謎題並推進劇情。 由 Antonio Antiochia & Veronika Slintak 開發，Polarware 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Antonio Antiochia & Veronika Slintak",
    "publisher": "Polarware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Triango_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Triango_1988_California_Dreams.2mg",
    "name": "Triango",
    "nameEn": "Triango",
    "year": "1988",
    "type": "game",
    "desc": "\"TrianGo\" is a 1988 board game developed by Staszek Bartkowski, Marcin Szostakowski, Maciej Markuszewski, Dorota Błaszczak, and distributed by California Dreams. It requires a 512K Apple IIgs. 這是一款棋類遊戲，電子化的傳統棋盤遊戲。 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "https://archive.org/download/wozaday_TrianGo_IIgs/00playable_screenshot.png"
  },
  {
    "id": "a2gs_Tunnels_of_Armageddon_1990_California_Dreams",
    "emu": "apple2gs",
    "file": "Tunnels_of_Armageddon_1990_California_Dreams.2mg",
    "name": "Tunnels of Armageddon",
    "nameEn": "Tunnels of Armageddon",
    "year": "1990",
    "type": "game",
    "desc": "\"Tunnels of Armageddon\" is a 1989 action game developed by Jarek Achinger, Adam Skorupiński, Mirek Zabłocki, Krzysiek Koziarski, Zbych Dąbrowski, Dorota Błaszczak, Marcin Grzegorzewski, Dick Vohlers, Tomek Meuś, and distributed by California Dreams. This is version 1.0. It requires a 512K Apple IIgs. 這是一款快節奏的動作遊戲，需要玩家具備良好的反應能力和操作技巧。 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Uninvited_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
	"file2": "00playable2.woz",
    "name": "不速之客",
    "nameEn": "Uninvited",
    "year": "1988",
    "type": "game",
    "desc": "這是一款恐怖冒險遊戲，玩家在一座鬧鬼的房子中探索並尋找失蹤的兄弟。遊戲以其陰森的氛圍和點擊式介面而著稱。由 ICOM Simulations 開發，Mindscape 發行。Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "e2gs_0528_Vegas_Craps_v1.0",
    "emu": "apple2gs",
    "file": "0528_Vegas_Craps_v1.0.po",
    "name": "Vegas Craps",
    "nameEn": "Vegas Craps",
    "year": "1988",
    "type": "game",
    "desc": "Apple IIgs: Vegas Craps (1988)(California Dreams) 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "a2gs_Vegas_Gambler_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Vegas_Gambler_1988_California_Dreams.2mg",
    "name": "Vegas Gambler",
    "nameEn": "Vegas Gambler",
    "year": "1988",
    "type": "game",
    "desc": "\"Vegas Gambler\" is a 1988 simulation game developed by Marek Jackiewicz, Andrzej Miciłkiewicz, Marcin Szostakowski, Maciej Markuszewski, and Dorota Błaszczak, and distributed by California Dreams. It requires a 512K Apple IIgs. 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_War_in_Middle_Earth_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "War in Middle Earth",
    "nameEn": "War in Middle Earth",
    "year": "1989",
    "type": "game",
    "desc": "\"War in Middle Earth\" is a 1989 adventure game developed by Ron Harris, Robert Clardy, Alan B. Clark, Graeme Devine, Mike Branham, Lloyd Ollmann, Jr., John Conley, Jim McBride, Michael Park, David Schroeder, Michael Ormsby, Mike Christy, Ann Dickens Clardy, Marcus Streets, Mark Riley, and Mike Singleton, and distributed by Melbourne House. It requires a 768K Apple IIgs ROM01 or later. 由 Synergistic Software 開發，Melbourne House 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Synergistic Software",
    "publisher": "Melbourne House",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Windwalker_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_1171_Windwalker_Disk_1/1171_Windwalker_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_1172_Windwalker_Disk_2/1172_Windwalker_Disk_2.po",
    "name": "Windwalker",
    "nameEn": "Windwalker",
    "year": "1990",
    "type": "game",
    "desc": "\"Windwalker\" is a 1990 roleplaying game developed by Greg Malone, Dallas Snell, Jeff Hillhouse, Dave Eresian, Richard Filoramo, Lester Humphreys, Jason Linhart, Stephen Linhart, Kiri Naiman, Keith Winston, Jeff Dee, Glen Johnson, Denis Loubet, Keith Berdak, Bill Clarke, and Doug Hewitt, and distributed by Origin Systems. It requires a 768K Apple IIgs ROM01 or later. 這是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。 由 Greg Malone 開發，Origin 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Greg Malone",
    "publisher": "Origin",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Winter_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "冬季運動會",
    "nameEn": "Winter Games",
    "year": "1987",
    "type": "game",
    "desc": "\"Winter Games\" is a 1987 sports game developed by Westwood Studios and distributed by Epyx. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 Westwood & IT 開發，Epyx 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Westwood & IT",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Wolfenstein_3D_v1.1_1997_Logicware_FW",
    "emu": "apple2gs",
    "file": "00_DualBootHelper_qkumba.dsk",
    "name": "Wolfenstein 3D",
    "nameEn": "Wolfenstein 3D",
    "year": "1998",
    "type": "game",
    "desc": "Apple IIgs: Wolfenstein 3D v1.1 (1997)(Logicware)(FW) 由 Rebecca Heineman, Eric Shepherd & NinjaForce 開發，Logicware 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。",
    "developer": "Rebecca Heineman, Eric Shepherd & NinjaForce",
    "publisher": "Logicware",
    "file2": "Wolfenstein_3D_v1.1_1997_Logicware_FW.2mg",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_World_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "世界運動會",
    "nameEn": "World Games",
    "year": "1987",
    "type": "game",
    "desc": "\"World Games\" is a 1987 sports game developed by Westwood and distributed by Epyx. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 Westwood & IT 開發，Epyx 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Westwood & IT",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_World_Tour_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "World Tour Golf",
    "nameEn": "World Tour Golf",
    "year": "1987",
    "type": "game",
    "desc": "\"World Tour Golf\" is a 1987 sports game developed by Evan & Nicky Robinson and Paul Reiche III, ported to the Apple IIgs by John Selhorst, and distributed by Electronic Arts. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 John Selhorst & Tanager Software Productions 開發，Electronic Arts 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "John Selhorst & Tanager Software Productions",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Xenocide_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Xenocide",
    "nameEn": "Xenocide",
    "year": "1989",
    "type": "game",
    "desc": "\"Xenocide\" is a 1989 action game developed by Brian Greenstone and Dave Triplett, and distributed by Micro Revelations. It requires a 512K Apple IIgs. 由 Pangea Software 開發，Micro Revelations 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Pangea Software",
    "publisher": "Micro Revelations",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Zany_Golf",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "瘋狂高爾夫",
    "nameEn": "Zany Golf",
    "year": "1988",
    "type": "game",
    "desc": "\"Zany Golf\" is a 1988 sports game developed by Will Harvey, Jim Nitchals, Ian Gooding, and Doug Fulton, and distributed by Electronic Arts. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 Sandcastle (Will Harvey, Ian Nitchal & Doug Fulton) 開發，Electronic Arts 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Sandcastle (Will Harvey, Ian Nitchal & Doug Fulton)",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Where_in_the_USA_is_Carmen_Sandiego_800K",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Where in the USA is Carmen Sandiego?",
    "nameEn": "Where in the USA is Carmen Sandiego?",
    "year": "1990",
    "type": "edu",
    "desc": "\"Where in the USA is Carmen Sandiego\" is a 1990 educational program developed by Ken Bull, Gene Portwood, and Lauren Elliot, and distributed by Broderbund Software. It requires an Apple IIgs, //c+, or a 128K //e with a compatible drive controller card. 由 Sculptured Software (Peter Adams) 開發，Broderbund 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Sculptured Software (Peter Adams)",
    "publisher": "Broderbund",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Where_in_the_World_is_Carmen_Sandiego_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Where in the World is Carmen Sandiego?",
    "nameEn": "Where in the World is Carmen Sandiego?",
    "year": "1989",
    "type": "edu",
    "desc": "\"Where in the World is Carmen Sandiego?\" is a 1989 educational game developed by Gene Portwood, Lauren Elliott, Loring Vogel, Leila Bronstein, Don Albrecht, and Michelle McBride, and distributed by Broderbund Software. It requires a 512K Apple IIgs. 由 Loring Vogel 開發，Broderbund 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Loring Vogel",
    "publisher": "Broderbund",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  }
];
