/**
 * Apple IIgs 遊戲庫 (Wikipedia 描述更新版)
 * 生成時間: 2025/12/21 下午10:14:18
 * 遊戲數量: 123
 * 
 * 更新內容:
 * - 移除標題中的 "IIgs"
 * - "The" 開頭的標題改成放在後面
 * - name = 英文名稱, nameCh = 中文名稱
 * - 以英文排序
 * - Wikipedia 描述自動更新
 */

window.games = [
  {
    "id": "BrutalDeluxeSoftware_lr",
    "emu": "apple2gs",
    "file": "https://www.brutaldeluxe.fr/products/apple2gs/loderunner/disks/loderunneriigs.zip/lr_system.po",
    "file2": "https://www.brutaldeluxe.fr/products/apple2gs/loderunner/disks/loderunneriigs.zip/lr_program.po",
    "name": "Lode Runner 2024",
    "year": "2024",
    "type": "game",
    "desc": "Lode Runner is a puzzle-platform game developed by Doug Smith and published by Broderbund in 1983. Its gameplay mechanics are similar to Space Panic from 1980. The player controls a character who must collect all the gold pieces in a level and reach the end while being chased by a number of enemies. It is one of the first games to include a level editor.",
    "descCh": "超級運動員 (Lode Runner)是一款於1983年由Doug Smith開發、Broderbund發行的經典平台解謎動作遊戲。玩家操作主角在多個關卡中收集所有金塊，再到達出口過關，途中要利用挖洞策略避開敵人追擊。此遊戲是最早具有關卡編輯器功能的作品之一。本作為Antoine Vignau 與 Olivier Zardini 於2024年為Apple IIgs開發，並由 Tozai Games 製作。",
    "developer": "Tozai Games",
    "publisher": "Brutal Deluxe Software",
    "screenshot": "https://www.brutaldeluxe.fr/products/apple2gs/loderunner/images/lr_title.jpg",
    "nameCh": "超級運動員"
  },
  {
    "id": "wozaday_4th_and_Inches_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "4th & Inches",
    "year": "1988",
    "type": "game",
    "desc": "4th & Inches is an American football sports game by Accolade. It was released for the Commodore 64 in 1987 and ported to Apple IIGS, MS-DOS, Amiga, and Mac OS by Sculptured Software in 1988. It was designed by Accolade co-founder, Bob Whitehead. An expansion pack, Team Construction Disk, was released in 1988.",
    "developer": "Tony Manso & Sculptured Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "關鍵一碼"
  },
  {
    "id": "a2gs_Aaargh_1988_Arcadia_Software",
    "emu": "apple2gs",
    "file": "Aaargh_1988_Arcadia_Software.2mg",
    "name": "Aaargh!",
    "year": "1988",
    "type": "game",
    "desc": "Aaargh! is a single-player action video game in which the player controls a giant monster with the goal of obtaining eggs by destroying buildings in different cities across a lost island.",
    "descCh": "這是一款快節奏的動作遊戲，玩家控制巨大怪獸在城市中大肆破壞。由 Synergistic Software 開發，Arcadia Software 發行。",
    "developer": "Synergistic Software",
    "publisher": "Arcadia Software",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "怪獸大暴走"
  },
  {
    "id": "a2gs_Airball_1989_MicroDeal",
    "emu": "apple2gs",
    "file": "Airball_1989_MicroDeal.2mg",
    "name": "Airball",
    "year": "1989",
    "type": "game",
    "desc": "Players control a balloon as it navigates a complex maze. The game is known for its unique physics engine and challenging level design.",
    "descCh": "Airball是一款快節奏的動作遊戲，玩家控制一個氣球在複雜的迷宮中冒險。遊戲以其獨特的物理引擎和挑戰性的關卡設計而著稱。由 Jason Harper 開發，MicroDeal 發行。",
    "developer": "Jason Harper",
    "publisher": "MicroDeal",
    "screenshot": "https://archive.org/download/wozaday_Airball_IIgs/00playable_screenshot.png",
    "nameCh": "氣球歷險"
  },
  {
    "id": "wozaday_Alien_Mind",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Alien Mind",
    "year": "1988",
    "type": "game",
    "desc": "Alien Mind is an action-adventure game for the Apple IIGS, published and released by PBI Software in 1988. It is the final game from PBI, and notable as a GS-only title, in taking advantage of the graphics and sound capabilities of the machine to present an arcade style game.",
    "developer": "Rob Karr & Matt Crysdale",
    "publisher": "PBI Software",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "異形心靈"
  },
  {
    "id": "wozaday_Ancient_Glory_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Ancient Glory",
    "year": "1993",
    "type": "game",
    "desc": "Ancient Glory is a 1993 action game developed by Logical Design Works, Westwood Associates and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Logical Design Works, Westwood Associates",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "遠古榮光"
  },
  {
    "id": "e2gs_0487_Ancient_Land_of_Ys_Disk_1",
    "emu": "apple2gs",
    "file": "0487_Ancient_Land_of_Ys_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0488_Ancient_Land_of_Ys_Disk_2/0488_Ancient_Land_of_Ys_Disk_2.po",
    "name": "Ancient Land of Ys",
    "year": "1989",
    "type": "game",
    "desc": "Ys I: Ancient Ys Vanished, also known as Ys: Ancient Ys Vanished - Omen, Ys: The Vanished Omens, Ancient Land of Ys or simply Ys, is a 1987 action role-playing game developed by Nihon Falcom. It is the first installment in the Ys series.",
    "developer": "Designer Software",
    "publisher": "Kyodai",
    "screenshot": "https://www.video-games-museum.com/en/screenshots/Apple%20II%20GS/1/55909-title-Ancient-Land-of-Ys.jpg",
    "nameCh": "伊蘇古國"
  },
  {
    "id": "wozaday_Arkanoid_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Arkanoid II: Revenge of Doh",
    "year": "1989",
    "type": "game",
    "desc": "Arkanoid: Revenge of Doh is an arcade game released by Taito in 1987 as a sequel to Arkanoid. User controls a bat at the bottom of the screen and uses it to catch and direct a ball so as to hit all the bricks which are arranged at the top of the screen.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "快打磚塊2"
  },
  {
    "id": "a2gs_As_the_Link_Turns_1988_Rogue_Systems_SW",
    "emu": "apple2gs",
    "file": "As_the_Link_Turns_1988_Rogue_Systems_SW.2mg",
    "name": "As the Link Turns",
    "year": "1988",
    "type": "game",
    "desc": "As The Link Turns: Operation Bug is a single-player arcade shooter for Apple IIgs. Players wear an antigravity bodysuit and control a crosshair to destroy enemies—bugs, RAM chips, and angry disks—within 2 minutes 15 seconds. The game combines fast-paced arcade action with Apple-specific humor and encourages high-score chasing through its brief, intense playtime.",
    "developer": "Parik Rao & Scott Pease (Rogue Systems)",
    "publisher": "",
    "screenshot": "https://cdn.mobygames.com/screenshots/16854153-as-the-link-turns-operation-bug-apple-iigs-shooting-creatures.png",
    "nameCh": "繞著連結轉"
  },
  {
    "id": "wozaday_Balance_of_Power_1990_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Balance of Power: The 1990 Edition",
    "year": "1989",
    "type": "game",
    "desc": "Balance of Power: The 1990 Edition is a sequel to the computer strategy game Balance of Power.",
    "developer": "Chris Crawford",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "權力平衡: 1990版"
  },
  {
    "id": "wozaday_The_Bards_Tale_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Bard's Tale, The",
    "year": "1988",
    "type": "game",
    "desc": "The Bard's Tale is a fantasy role-playing video game franchise created by Michael Cranford and developed by Brian Fargo's Interplay Productions and inXile Entertainment . The initial title of the series was Tales of the Unknown. The Bard's Tale II: The Destiny Knight dropped the Tales of the Unknown series title, as did all ports of the original game after 1988.",
    "descCh": "The Bard's Tale 是一款角色扮演遊戲，玩家可以培養角色、學習技能並體驗豐富的故事情節。由 Rebecca Heineman 開發，Electronic Arts 發行。",
    "developer": "Rebecca Heineman",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "冰城傳奇"
  },
  {
    "id": "a2gs_Battle_Chess_1989_Interplay",
    "emu": "apple2gs",
    "file": "Battle_Chess_1989_Interplay.2mg",
    "name": "Battle Chess",
    "year": "1989",
    "type": "game",
    "desc": "Battle Chess is a video game version of chess with 2.5D graphics and fighting animations showing the result of one piece moving onto the square of another. In 1991, Battle Chess Enhanced was released by Interplay for IBM PC compatibles and Macintosh with improved VGA graphics and a symphonic musical score played from the CD-ROM.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "戰鬥西洋棋"
  },
  {
    "id": "a2gs_Beyond_Zork_1988_Infocom",
    "emu": "apple2gs",
    "file": "Beyond_Zork_1988_Infocom.2mg",
    "name": "Beyond Zork",
    "year": "1988",
    "type": "game",
    "desc": "Beyond Zork: The Coconut of Quendor is an interactive fiction video game written by Brian Moriarty and released by Infocom in 1987. It was one of the last games in the Zork series developed by Infocom.",
    "developer": "Brian Moriarty",
    "publisher": "Infocom",
    "screenshot": "https://upload.wikimedia.org/wikipedia/en/0/0a/Beyond_Zork_game_box_cover.jpg",
    "nameCh": "魔域之外"
  },
  {
    "id": "wozaday_The_Black_Cauldron_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Black Cauldron, The",
    "year": "1987",
    "type": "game",
    "desc": "Black Cauldron is a 1987 adventure game developed by Al Lowe and published by Sierra.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "黑神鍋"
  },
  {
    "id": "wozaday_Blackjack_Academy_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Blackjack Academy",
    "year": "1988",
    "type": "game",
    "desc": "Blackjack Academy is a 1988 cards game developed by Westwood and published by Micro Illusions.",
    "developer": "Westwood",
    "publisher": "Micro Illusions",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "21點學院"
  },
  {
    "id": "wozaday_Blockout_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Block Out",
    "year": "1989",
    "type": "game",
    "desc": "Blockout is a puzzle video game published in 1989 by California Dreams. It was developed in Poland by Aleksander Ustaszewski and Mirosław Zabłocki. American Technos published an arcade version. Blockout is an unlicensed, 3D version of Tetris.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "3D俄羅斯"
  },
  {
    "id": "wozaday_Bridge_6_0_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Bridge 6.0",
    "year": "1989",
    "type": "game",
    "desc": "Bridge 6.0 is a contract or duplicate Bridge program. You and your computer partner play against two computer opponents.",
    "developer": "Arthur Walsh & Roger Harnish",
    "publisher": "Artworx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "橋牌6.0"
  },
  {
    "id": "a2gs_Bubble_Ghost_1988_Accolade",
    "emu": "apple2gs",
    "file": "Bubble_Ghost_1988_Accolade.2mg",
    "name": "Bubble Ghost",
    "year": "1988",
    "type": "game",
    "desc": "Bubble Ghost is a puzzle video game created by Christophe Andréani for the Atari ST in 1987. The player controls a ghost who by blowing, guides a floating bubble throughout a number of halls in a haunted house, while avoiding obstacles that can make the bubble pop.",
    "developer": "ERE Informatique",
    "publisher": "Accolade",
    "screenshot": "https://archive.org/download/wozaday_Bubble_Ghost_IIgs/00playable_screenshot.png",
    "nameCh": "泡泡幽靈"
  },
  {
    "id": "wozaday_California_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "California Games",
    "year": "1988",
    "type": "game",
    "desc": "California Games is a 1987 sports video game developed and published by Epyx for the Apple II and Commodore 64. Branching from their Summer Games and Winter Games series, it is a collection of outdoor sports purportedly popular in California. It was followed by the sequel California Games II in 1990.",
    "developer": "Designer Software (Jimmy Huey)",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "加州運動會"
  },
  {
    "id": "a2gs_Captain_Blood_1989_Mindscape",
    "emu": "apple2gs",
    "file": "Captain_Blood_1989_Mindscape.2mg",
    "name": "Captain Blood",
    "year": "1989",
    "type": "game",
    "desc": "Captain Blood is a 1989 simulation game developed by Philippe Ulrich, Didier Bouchon, Jean-Michel Jarre, Alexis Martial, and Michael Rho, and distributed by Mindscape.",
    "developer": "ERE Informatique (Alexis Martial & Jean-Michel Jarre)",
    "publisher": "Mindscape",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "浴血船長 1989"
  },
  {
    "id": "a2gs_Carte_Primus_1989_Manthey_d_SW",
    "emu": "apple2gs",
    "file": "Carte_Primus_1989_Manthey_d_SW.2mg",
    "name": "Carte Primus",
    "year": "1989",
    "type": "game",
    "desc": "Carte Primus (1989) - A collection of five card games: Cribbage, Gin Rummy, Hearts, Pinochle, Pitch.",
    "developer": "David Manthey",
    "publisher": "David Manthey",
    "screenshot": "https://images.igdb.com/igdb/image/upload/t_720p/scdrts.jpg",
    "nameCh": "首張王牌"
  },
  {
    "id": "wozaday_Cavern_Cobra_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Cavern Cobra",
    "year": "1987",
    "type": "game",
    "desc": "Cavern Cobra is a 1987 shoot 'em up game developed by Greg Hale and published by PBI Software.",
    "developer": "Greg Hale",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "洞穴眼鏡蛇"
  },
  {
    "id": "wozaday_Club_Backgammon_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Club Backgammon",
    "year": "1988",
    "type": "game",
    "desc": "Club Backgammon is a 1988 board game developed by Logical Design Works and published by California Dreams.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "雙陸棋俱樂部"
  },
  {
    "id": "a2gs_Cogito_1992_Brutal_Deluxe_FW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Cogito",
    "year": "1993",
    "type": "game",
    "desc": "The Cogito game for the Apple IIGS is a freeware puzzle/adventure game, originally by Jerome Cretaux, adapted for the IIGS in 1994 by Antoine Vignau & Olivier Zardini, featuring a unique \"brain\" mechanic where you control neurons to solve puzzles and guide a character, known for its distinctive style and being a beloved retro title on the platform.",
    "developer": "Antoine Vignau & Olivier Zardini (Brutal Deluxe)",
    "publisher": "Brutal Deluxe",
    "file2": "Cogito_1992_Brutal_Deluxe_FW.2mg",
    "screenshot": "https://www.brutaldeluxe.fr/images/coglog12.gif",
    "nameCh": "Cogito"
  },
  {
    "id": "wozaday_Columns_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Columns GS",
    "year": "1991",
    "type": "game",
    "desc": "Columns is a 1991 puzzle game developed by Kenrick Mock (Sound Barrier Systems) and published by . It requires an Apple IIgs.",
    "developer": "Kenrick Mock (Sound Barrier Systems)",
    "publisher": "",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "寶石方塊GS"
  },
  {
    "id": "a2gs_Crystal_Quest_1989_Cassidy_Greene",
    "emu": "apple2gs",
    "file": "Crystal_Quest_1989_Cassidy__Greene.2mg",
    "name": "Crystal Quest",
    "year": "1989",
    "type": "game",
    "desc": "Crystal Quest is an action game written by Patrick Buckland for the Macintosh and published by Casady & Greene in 1987. It was ported to the Apple IIGS in 1989 by Rebecca Heineman. Ports were also made to the Amiga, Game Boy, iOS, and Palm. It was the first game to support the color displays of the Macintosh II.",
    "developer": "Rebecca Heineman",
    "publisher": "Cassidy & Greene",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "水晶任務"
  },
  {
    "id": "wozaday_Dark_Castle_1989_09_22_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dark Castle 1989-09-22",
    "year": "1989",
    "type": "game",
    "desc": "\"Dark Castle\" is a 1989 action game developed by Lane Roath and published by Three Sixty. It requires an Apple IIgs.",
    "developer": "Lane Roath",
    "publisher": "Three Sixty",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "黑暗城堡 1989-09-22"
  },
  {
    "id": "wozaday_Deja_Vu_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Déjà Vu II: Lost in Las Vegas",
    "year": "1989",
    "type": "game",
    "desc": "Deja Vu II: Lost in Las Vegas is a 1989 adventure game developed by ICOM Simulations and published by Mindscape. It requires an Apple IIgs.",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "似曾相識2：迷失拉斯維加斯"
  },
  {
    "id": "wozaday_Destroyer_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Destroyer",
    "year": "1987",
    "type": "game",
    "desc": "Destroyer is a 1987 simulation game developed by Michael Kosaka & Chuck Sommerville and published by Epyx.",
    "developer": "Michael Kosaka & Chuck Sommerville",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "驅逐艦"
  },
  {
    "id": "wozaday_Downhill_Challenge_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Downhill Challenge",
    "year": "1989",
    "type": "game",
    "desc": "Downhill Challenge is a skiing video game developed by Microïds. It was published 1988 in the US by Broderbund and in France by Loriciel as Super Ski. In the UK it had an Eddie the Eagle license. The third-person, 2.5D game has 4 modes: Downhill, Slalom, Giant Slalom and Ski Jump. It can be played up to 5 players taking turns with their results compared at the end.",
    "developer": "Microids",
    "publisher": "Broderbund",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "下坡挑戰賽"
  },
  {
    "id": "wozaday_Dragon_Wars_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dragon Wars",
    "year": "1990",
    "type": "game",
    "desc": "Dragon Wars is a fantasy role-playing video game developed by Rebecca Heineman, published by Interplay Productions in 1989, and distributed by Activision.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "龍之戰"
  },
  {
    "id": "wozaday_Dream_Zone_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dream Zone",
    "year": "1988",
    "type": "game",
    "desc": "Dream Zone is an adventure game developed by JAM Software and published by Baudville. It was released in 1988 for the Apple II and Apple IIGS, followed by versions for MS-DOS, the Amiga, and the Atari ST.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Baudville",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "職業學校"
  },
  {
    "id": "a2gs_Dueltris_1992_DreamWorld_FW_a_non_boot",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "DuelTris",
    "year": "1992",
    "type": "game",
    "desc": "Dueltris is a 1 - 2 player competitive Tetris clone for the Apple IIgs. Different shaped blocks fall from the top of the screen, and the player must align them in rows. When a row is completed, the line is deleted. If the blocks reach the top of the screen, it's game over. Players can also receive bombs and guns that destroy a few blocks. Both players' play screens are displayed simultaneously. During competitive play, the player can compete against a computer of different difficulty, or another human opponent.",
    "developer": "Steven Chiang, Dave Seah & James Brookes",
    "publisher": "DreamWorld",
    "file2": "Dueltris_1992_DreamWorld_FW_a_non_boot.2mg",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "對戰俄羅斯"
  },
  {
    "id": "a2gs_Dungeon_Master_1989_FTL",
    "emu": "apple2gs",
    "file": "Dungeon_Master_1989_FTL.2mg",
    "name": "Dungeon Master",
    "year": "1989",
    "type": "game",
    "desc": "In the Dungeons & Dragons role-playing game, the Dungeon Master is the game organizer and participant in charge of creating the details and challenges of a given adventure, while maintaining a realistic continuity of events. In effect, the Dungeon Master controls all aspects of the game, except for the actions of the player characters, and describes to the players what their characters experience.",
    "developer": "Don Jordan",
    "publisher": "FTL",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "地下城主"
  },
  {
    "id": "wozaday_Fast_Break_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Fast Break",
    "year": "1989",
    "type": "game",
    "desc": "Fast Break simulates the 3 on 3 game of basketball, allowing one or two players to control the players with either the keyboard or a joystick. The game allows to customize player's team by choosing any of the pre-defined players with their unique strength and weaknesses.",
    "developer": "Greg Hospelhorn & George Wong",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "籃球快攻"
  },
  {
    "id": "wozaday_Final_Assault_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Final Assault",
    "year": "1988",
    "type": "game",
    "desc": "Final Assault, known as Chamonix Challenge in Europe, originally Bivouac in French, is a mountaineering simulation developed by Infogrames in 1987 and distributed by Infogrames in Europe and Epyx in the American continent, for the Amiga, Amstrad CPC, Apple IIGS, Atari ST, Commodore 64, MS-DOS, Thomson MO6, Thomson TO8 and ZX Spectrum. The original release of the game was copy protected.",
    "developer": "Infogrames",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "最終攻頂"
  },
  {
    "id": "a2gs_Firepower_1989_MicroIllusions",
    "emu": "apple2gs",
    "file": "Firepower_1989_MicroIllusions.2mg",
    "name": "Firepower",
    "year": "1989",
    "type": "game",
    "desc": "Firepower is the military capability to direct force at an enemy. It involves the whole range of potential weapons. The concept is generally taught as one of the three key principles of modern warfare wherein the enemy forces are destroyed or have their will to fight negated by sufficient and preferably overwhelming use of force as a result of combat operations.",
    "developer": "Stephen Lepisto",
    "publisher": "MicroIllusions",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "火力全開"
  },
  {
    "id": "wozaday_Full_Metal_Planete_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Full Metal Planète",
    "year": "1993",
    "type": "game",
    "desc": "Full Metal Planète is a board game. Players play as mining companies on the Full Metal Planet, a planet which is rich in mining resources, but also unstable. They try to amass the maximum amount of ore and evacuate it into orbit before the destruction of the planet, thwarting other players and dealing with the destructive tides of the planet.",
    "developer": "Brainstorm Software (Francois Uhrich & Nicolas Bergeret)",
    "publisher": "Infogrames",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "金屬星球"
  },
  {
    "id": "wozaday_GATE_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "GATE",
    "year": "1991",
    "type": "game",
    "desc": "A gate is an opening in a wall or fence fitted with a moveable barrier allowing it to be closed.",
    "developer": "Bright Software (Joerg Kienzle, Yann Le Tensorer & Henrik Gudat)",
    "publisher": "Toolbox & Seven Hills",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "GATE"
  },
  {
    "id": "wozaday_Gauntlet_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gauntlet",
    "year": "1988",
    "type": "game",
    "desc": "Gauntlet or the gauntlet may refer to:",
    "developer": "Atari Games",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Gauntlet"
  },
  {
    "id": "a2gs_GBA_Championship_Basketball_Two-On-Two_1987_Gamestar_Activision",
    "emu": "apple2gs",
    "file": "GBA_Championship_Basketball_Two-On-Two_1987_Gamestar_Activision.2mg",
    "name": "GBA Championship Basketball: Two on Two",
    "year": "1987",
    "type": "game",
    "desc": "GBA Championship Basketball: Two-on-Two is a sports video game for IBM PC compatibles Amiga, Apple II, Apple IIGS, Amstrad CPC, Atari ST, ZX Spectrum, and Commodore 64. It was developed by Dynamix and published in 1986 by Activision.",
    "developer": "Gamestar (Paul Terry & Jack Thornton)",
    "publisher": "Activision",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "GBA Championship Basketball: Two on Two"
  },
  {
    "id": "a2gs_Cribbage_Gin_King_1990_The_Software_Toolworks",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Gin King / Cribbage King",
    "year": "1990",
    "type": "game",
    "desc": "\"Gin King / Cribbage King\" is a 1989 board game developed by Mark Manyen, Don Laabs, David M. Linnehan, and Elizabeth Scafati, and distributed by The Software Toolworks. It requires a 1MB Apple IIgs. 由 Mark Manyen 開發，Software Toolworks 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Mark Manyen",
    "publisher": "Software Toolworks",
    "file2": "Cribbage__Gin_King_1990_The_Software_Toolworks.2mg",
    "screenshot": "https://archive.org/download/wozaday_Gin_King_Cribbage_King_IIgs/00playable_screenshot.png",
    "nameCh": "Gin King / Cribbage King"
  },
  {
    "id": "wozaday_Gnarly_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gnarly Golf",
    "year": "1989",
    "type": "game",
    "desc": "\"Gnarly Golf\" is a 1989 sports game developed by Visual Concepts (Jim Coliz Jnr & Darren Bartlett) and published by Britannica / Fanfare. It requires an Apple IIgs.",
    "developer": "Visual Concepts (Jim Coliz Jnr & Darren Bartlett)",
    "publisher": "Britannica / Fanfare",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Gnarly Golf"
  },
  {
    "id": "wozaday_Grand_Prix_Circuit_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Grand Prix Circuit",
    "year": "1989",
    "type": "game",
    "desc": "Grand Prix Circuit may refer to:Grand Prix Circuit, a 1988 motor sports video game Grand Prix tennis circuit, one of the two major professional world tennis circuits of the 1970s and 1980s",
    "developer": "Distinctive Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Grand Prix Circuit"
  },
  {
    "id": "wozaday_Halls_of_Montezuma_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Halls of Montezuma",
    "year": "1990",
    "type": "game",
    "desc": "Halls of Montezuma: A Battle History of the U.S. Marine Corps is a computer wargame developed by Strategic Studies Group in 1987 for the Apple II. Ports were released for the Commodore 64, Amiga, MS-DOS, and Apple IIGS.",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Halls of Montezuma"
  },
  {
    "id": "wozaday_Hardball_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Hardball!",
    "year": "1987",
    "type": "game",
    "desc": "Hardball may refer to:",
    "developer": "Distinctive Software (Dan Thompson)",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Hardball!"
  },
  {
    "id": "a2gs_Hostage_1990_Mindscape",
    "emu": "apple2gs",
    "file": "Hostage_1990_Mindscape.2mg",
    "name": "Hostage",
    "year": "1990",
    "type": "game",
    "desc": "A hostage is a person seized by an abductor in order to compel another party, one which places a high value on the liberty, well-being and safety of the person seized—such as a relative, employer, law enforcement, or government—to act, or refrain from acting, in a certain way, often under threat of serious physical harm or death to the hostage after expiration of an ultimatum.",
    "developer": "Infogrames",
    "publisher": "Mindscape",
    "screenshot": "https://archive.org/download/wozaday_Hostage_Rescue_Mission_IIgs/00playable_screenshot.png",
    "nameCh": "Hostage"
  },
  {
    "id": "wozaday_Hover_Blade_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "https://archive.org/download/wozaday_Hover_Blade_IIgs/Hover%20Blade%20IIgs%20%28woz-a-day%20collection%29.zip/Hover%20Blade%20IIgs%20%28woz-a-day%20collection%29%2FHover%20Blade%20IIgs%20-%20Disk%202.woz",
    "name": "Hover Blade",
    "year": "1991",
    "type": "game",
    "desc": "\"Hover Blade\" is a 1991 action game developed by Shiraz Akmal & Eric Boden and published by MCX. It requires an Apple IIgs.",
    "developer": "Shiraz Akmal & Eric Boden",
    "publisher": "MCX",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Hover Blade"
  },
  {
    "id": "wozaday_The_Hunt_for_Red_October_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Hunt for Red October, The",
    "year": "1989",
    "type": "game",
    "desc": "The Hunt for Red October is the debut novel by American author Tom Clancy, first published on October 1, 1984, by the Naval Institute Press.",
    "developer": "John Brooks, Todd Daugherty & Alex Villagran",
    "publisher": "Software Toolworks",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "The Hunt for Red October"
  },
  {
    "id": "a2gs_Impossible_Mission_II_1989_Epyx",
    "emu": "apple2gs",
    "file": "Impossible_Mission_II_1989_Epyx.2mg",
    "name": "Impossible Mission 2",
    "year": "1989",
    "type": "game",
    "desc": "Impossible Mission II is a video game developed by Novotrade and published by Epyx in 1988. It was released for the Commodore 64, ZX Spectrum, Amstrad CPC, Enterprise 128, Nintendo Entertainment System, MS-DOS, Atari ST, Apple II with at least 128K, Apple IIGS, and Amiga.",
    "developer": "Novotrade",
    "publisher": "Epyx",
    "screenshot": "https://archive.org/download/wozaday_Impossible_Mission_II_IIgs/00playable_screenshot.png",
    "nameCh": "不可能的任務 2"
  },
  {
    "id": "wozaday_Invisible_Bugs_800K",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Invisible Bugs",
    "year": "2021",
    "type": "game",
    "desc": "\"BuGS\" is a 2021 shoot 'em up game developed by Jeremy Rand and published by . It requires an Apple IIgs.",
    "developer": "Jeremy Rand",
    "publisher": "",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Invisible Bugs"
  },
  {
    "id": "a2gs_Kaleidokubes_1989_Artworx",
    "emu": "apple2gs",
    "file": "Kaleidokubes_1989_Artworx.2mg",
    "name": "Kaleidokubes",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Kaleidokubes (1989)(Artworx) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Bob & Betsy Couch 開發，Artworx 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Bob & Betsy Couch",
    "publisher": "Artworx",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Kaleidokubes"
  },
  {
    "id": "wozaday_Keef_the_Thief_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0907_Keef_the_Thief_Disk_1/0907_Keef_the_Thief_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0908_Keef_the_Thief_Disk_2/0908_Keef_the_Thief_Disk_2.po",
    "name": "Keef the Thief",
    "year": "1989",
    "type": "game",
    "desc": "Keef the Thief: A Boy and His Lockpick is a video game developed by Naughty Dog and published by Electronic Arts. It was released in 1989 for the Apple IIGS and then later ported to the Amiga and MS-DOS. Keef the Thief is a comedic sword and sorcery role-playing game.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "盜賊基夫"
  },
  {
    "id": "wozaday_The_King_of_Chicago_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "King of Chicago, The",
    "year": "1989",
    "type": "game",
    "desc": "The King of Chicago is a 1986 action-adventure video game by Doug Sharp. Based on numerous Hollywood mobster movies, this game is set in the 1930s, but some sequences towards the end of the game take place in 1986. The Macintosh version of the game is animated using claymation, while other versions utilize drawn graphics.",
    "developer": "Doug Sharp",
    "publisher": "Cinemaware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "The King of Chicago"
  },
  {
    "id": "wozaday_The_Last_Ninja_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Last Ninja, The",
    "year": "1988",
    "type": "game",
    "desc": "The Last Ninja is an action-adventure game developed and published by System 3 in 1987 for the Commodore 64. It was converted to the Apple IIGS, MS-DOS, BBC Micro and Acorn Electron in 1988, the Apple II in 1989, the Amiga and Atari ST in 1990, and the Acorn Archimedes in 1991.",
    "developer": "System 3",
    "publisher": "Activision",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "The Last Ninja"
  },
  {
    "id": "wozaday_Leisure_Suit_Larry_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0283_Leisure_Suit_Larry_Disk_1/0283_Leisure_Suit_Larry_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0284_Leisure_Suit_Larry_Disk_2/0284_Leisure_Suit_Larry_Disk_2.po",
    "name": "Leisure Suit Larry in the Land of the Lounge Lizards",
    "year": "1987",
    "type": "game",
    "desc": "Leisure Suit Larry in the Land of the Lounge Lizards is a graphic adventure game, developed by Sierra On-Line, published in 1987. It was developed for the MS-DOS and the Apple II and later ported to the Amiga, Atari ST, Apple IIGS, Mac, and Tandy Color Computer 3. It utilizes the Adventure Game Interpreter engine.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Leisure Suit Larry in the Land of the Lounge Lizards"
  },
  {
    "id": "wozaday_Life_and_Death_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Life and Death",
    "year": "1989",
    "type": "game",
    "desc": "Life and death is a fundamental concept in the game of Go.",
    "developer": "Mark Manyen & Jacob P. Smith",
    "publisher": "Software Toolworks",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Life and Death"
  },
  {
    "id": "wozaday_The_Lost_Tribe_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Lost Tribe, The",
    "year": "1992",
    "type": "game",
    "desc": "Matthew Jonathan Darey is an English trance music producer and performer. Darey has sold over two million albums and singles with numerous top 40 chart hits.",
    "developer": "Steve Vance, Frank Andrews & Todd Harris",
    "publisher": "Lawrence Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Lost Tribe, The"
  },
  {
    "id": "a2gs_Mad_Match_1989_Baudville",
    "emu": "apple2gs",
    "file": "Mad_Match_1989_Baudville.2mg",
    "name": "Mad Match",
    "year": "1989",
    "type": "game",
    "desc": "Apple IIgs: Mad Match (1989)(Baudville) 由 Paul Gauthier 開發，Baudville 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Paul Gauthier",
    "publisher": "Baudville",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Mad Match"
  },
  {
    "id": "a2gs_Mancala_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Mancala_1988_California_Dreams.2mg",
    "name": "Mancala",
    "year": "1988",
    "type": "game",
    "desc": "Mancala is a family of two-player turn-based strategy board games played with small stones, beans, marbles or seeds and rows of holes or pits in the earth, a board or other playing surface. The objective is usually to capture all or some set of the opponent's pieces.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "https://archive.org/download/wozaday_Mancala_IIgs/00playable_screenshot.png",
    "nameCh": "Mancala"
  },
  {
    "id": "wozaday_Marble_Madness_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Marble Madness",
    "year": "1988",
    "type": "game",
    "desc": "Marble Madness is a 1984 platform game designed by Mark Cerny and published by Atari Games Inc. for arcades. Set in an isometric perspective, the game tasks the player with guiding a marble through six courses, populated with obstacles and enemies, within a time limit. The player controls the marble by using a trackball.",
    "developer": "Will Harvey",
    "publisher": "Electronic Arts",
    "screenshot": "https://archive.org/download/wozaday_Marble_Madness/00playable_screenshot.png",
    "nameCh": "Marble Madness"
  },
  {
    "id": "wozaday_Mazer_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mazer II",
    "year": "1992",
    "type": "game",
    "desc": "\"Mazer II\" is a 1992 action rpg game developed by Farfetch Software and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Farfetch Software",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Mazer II"
  },
  {
    "id": "wozaday_Mini_Putt_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Mini_Putt_The_Ultimate_Challenge_1988_Accolade/Mini_Putt_The_Ultimate_Challenge_1988_Accolade.2mg",
    "name": "Mini-Putt",
    "year": "1988",
    "type": "game",
    "desc": "Miniature golf is an offshoot of the sport of golf focusing solely on the putting aspect of its parent game. The aim of the game is to score the lowest number of points. It is played on courses consisting of a series of holes similar to those of its parent, but the holes are short.",
    "developer": "Ross Salas & Tanager Software Productions",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Mini-Putt"
  },
  {
    "id": "wozaday_Mixed_Up_Mother_Goose_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mixed-Up Mother Goose",
    "year": "1988",
    "type": "game",
    "desc": "Roberta Williams' Mixed-Up Mother Goose is an educational adventure game released by Sierra On-Line in 1987. It was the first multimedia game released on CD-ROM in 1991. A second game in the series, Mixed-Up Fairy Tales, was released in 1991.",
    "developer": "Roberta Williams",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Mixed-Up Mother Goose"
  },
  {
    "id": "wozaday_Monte_Carlo_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Monte_Carlo_1988_PBI_Software/Monte_Carlo_1988_PBI_Software.2mg",
    "name": "Monte Carlo",
    "year": "1987",
    "type": "game",
    "desc": "Monte Carlo is an official administrative area of Monaco, specifically the ward of Monte Carlo/Spélugues, where the Monte Carlo Casino is located. Informally, the name also refers to a larger district, the Monte Carlo Quarter, which besides Monte Carlo/Spélugues also includes the wards of La Rousse/Saint Roman, Larvotto/Bas Moulins and Saint Michel.",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Monte Carlo"
  },
  {
    "id": "a2gs_Neuromancer_1989_Interplay",
    "emu": "apple2gs",
    "file": "Neuromancer_1989_Interplay.2mg",
    "name": "Neuromancer",
    "year": "1989",
    "type": "game",
    "desc": "Neuromancer is a 1984 science fiction novel by American-Canadian author William Gibson. Set in a near-future dystopia, the narrative follows Case, a computer hacker enlisted into a crew by a powerful artificial intelligence and a traumatised former soldier to complete a high-stakes heist.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Neuromancer"
  },
  {
    "id": "a2gs_Omega_1990_Origin",
    "emu": "apple2gs",
    "file": "Omega_1990_Origin.2mg",
    "name": "Omega",
    "year": "1990",
    "type": "game",
    "desc": "Omega is the twenty-fourth and last letter in the Greek alphabet. In the Greek numeric system/isopsephy, it has a value of 800. The name of the letter was originally ὦ, but it was later changed to ὦ μέγα in the Middle Ages to distinguish it from omicron ⟨ο⟩, whose name means 'small o', as both letters had come to be pronounced. In modern Greek, its name has fused into ωμέγα.",
    "developer": "Micro Magic",
    "publisher": "Origin",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Omega"
  },
  {
    "id": "wozaday_Panzer_Battles_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Panzer Battles",
    "year": "1991",
    "type": "game",
    "desc": "Panzer Battles may refer to:Panzer Battles, a 1956 memoir Panzer Battles, a 1989 video game",
    "developer": "Roger Keating, Danny Stevens & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Panzer Battles"
  },
  {
    "id": "a2gs_Paperboy_1988_Mindscape",
    "emu": "apple2gs",
    "file": "Paperboy_1988_Mindscape.2mg",
    "name": "Paperboy",
    "year": "1988",
    "type": "game",
    "desc": "A paperboy is someone – often an older child or adolescent – who distributes printed newspapers to homes or offices on a regular route, usually by bicycle or automobile. In Western nations during the heyday of print newspapers during the early 20th century, this was often a young person's first job, perhaps undertaken before or after school.",
    "developer": "Atari Games",
    "publisher": "Mindscape",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "送報生"
  },
  {
    "id": "a2gs_Pipe_Dream_1990_Lucasfilm_Games",
    "emu": "apple2gs",
    "file": "Pipe_Dream_1990_Lucasfilm_Games.2mg",
    "name": "Pipe Dream",
    "year": "1990",
    "type": "game",
    "desc": "Pipe dream, a phrase describing a wild or unattainable plan, from Opium § Recreational use in Europe, the Middle East and the US, that may refer to:",
    "developer": "Visual Concepts",
    "publisher": "Lucasfilm Games",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Pipe Dream"
  },
  {
    "id": "a2gs_Pirates_1988_Microprose",
    "emu": "apple2gs",
    "file": "Pirates_1988_Microprose.2mg",
    "name": "Pirates!",
    "year": "1988",
    "type": "game",
    "desc": "Sid Meier's Pirates! is a video game created by Sid Meier for the Commodore 64 published by MicroProse in May 1987, and followed by versions for several other platforms. It was the first game to include the name \"Sid Meier\" in its title as an effort by MicroProse to attract fans of Meier's earlier games, most of which were combat vehicle simulation video games.",
    "developer": "Ed Magnin",
    "publisher": "Microprose",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "海盜！"
  },
  {
    "id": "wozaday_Police_Quest_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0334_Police_Quest_DIsk_1/0334_Police_Quest_DIsk_1.po",
    "file2": "https://archive.org/download/e2gs_0335_Police_Quest_Disk_2/0335_Police_Quest_Disk_2.po",
    "name": "Police Quest",
    "year": "1987",
    "type": "game",
    "desc": "Police Quest: In Pursuit of the Death Angel is a 1987 police procedural adventure video game developed and published by Jim Walls and Sierra On-Line. Police Quest follows police officer Sonny Bonds as he investigates a drug cartel in the town of Lytton, California.",
    "developer": "Jim Walls",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Police Quest"
  },
  {
    "id": "wozaday_Qix_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Qix_1990_Taito_US/Qix_1990_Taito_US.2mg",
    "name": "Qix",
    "year": "1990",
    "type": "game",
    "desc": "Qix is a 1981 puzzle video game developed by husband and wife team Randy and Sandy Pfeiffer and published by Taito America for arcades. Qix is one of a handful of games made by Taito's American division. The objective is to draw lines that close off parts of the rectangle to fill in a set amount of the playfield.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Qix"
  },
  {
    "id": "a2gs_Quest_for_the_Hoard_1991_Pegasoft_SW",
    "emu": "apple2gs",
    "file": "Quest_for_the_Hoard_1991_Pegasoft_SW.2mg",
    "name": "Quest for the Hoard",
    "year": "1991",
    "type": "game",
    "desc": "Apple IIgs: Quest for the Hoard (1991)(Pegasoft)(SW) 這是一款益智遊戲，通過解決各種謎題來挑戰玩家的邏輯思維。 由 Ken Burtch (Pegasoft) 製作。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Ken Burtch (Pegasoft)",
    "publisher": "",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "Quest for the Hoard"
  },
  {
    "id": "a2gs_Questron_II_1988_SSI",
    "emu": "apple2gs",
    "file": "Questron_II_1988_SSI.2mg",
    "name": "Questron II",
    "year": "1988",
    "type": "game",
    "desc": "Questron II a 1988 role-playing video game published by Strategic Simulations for the Apple II, Apple IIGS, Atari ST, Commodore 64, IBM PC compatibles, and Amiga. It is the sequel to 1984's Questron. The story and original design is credited to Quest Software, while the programming and artwork is credited to Westwood Associates.",
    "developer": "Westwood",
    "publisher": "Strategic Simulations",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Questron II"
  },
  {
    "id": "wozaday_Rastan",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Rastan",
    "year": "1990",
    "type": "game",
    "desc": "Rastan Saga, known as Rastan in North America, is a side-scrolling hack and slash arcade video game released by Taito in 1987. It was a critical and commercial success and was ported to home platforms.",
    "developer": "John Brooks",
    "publisher": "Taito America",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Rastan"
  },
  {
    "id": "a2gs_Reach_For_The_Stars_1988_SSG",
    "emu": "apple2gs",
    "file": "Reach_For_The_Stars_1988_SSG.2mg",
    "name": "Reach for the Stars",
    "year": "1988",
    "type": "game",
    "desc": "Reach for the Stars may refer to:\"Reach for the Stars\", a Cash Cash song for the Sega video game Sonic Colors \"Reach for the Stars\", 2012 \"Reach for the Stars\", 1961 \"Reach for the Stars\", 1984 \"Reach\", commonly referred to as \"Reach for the Stars\" Reach for the Stars, a 1981 CBS space-themed campaign Reach for the Stars, an Indian English-dubbed TV series Reach for the Stars, a 1983 science.",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Reach for the Stars"
  },
  {
    "id": "wozaday_Roadwar_2000_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Roadwar_2000_1987_SSI/Roadwar_2000_1987_SSI.2mg",
    "name": "Roadwar 2000",
    "year": "1987",
    "type": "game",
    "desc": "Roadwar 2000 is a 1986 video game published by Strategic Simulations It is a turn-based strategy game set in a post-apocalyptic future that resembles the world portrayed in the Mad Max films.",
    "developer": "Westwood",
    "publisher": "Strategic Simulations",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Roadwar 2000"
  },
  {
    "id": "wozaday_Rocket_Ranger_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0729_Rocket_Ranger_Disk_1/0729_Rocket_Ranger_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0730_Rocket_Ranger_Disk_2/0730_Rocket_Ranger_Disk_2.po",
    "name": "Rocket Ranger",
    "year": "1989",
    "type": "game",
    "desc": "Rocket Ranger is a 1988 action-adventure game developed and published by Cinemaware. The game's setting is based in the World War II era, allowing the player to control a US Army scientist and setting out to stop Nazi Germany from winning the war. The Rocket Ranger moniker stems from the rocket pack the player uses over the course of the game.",
    "developer": "Ed Magnin",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "火箭騎兵"
  },
  {
    "id": "a2gs_Sea_Strike_1987_PBI_Software",
    "emu": "apple2gs",
    "file": "Sea_Strike_1987_PBI_Software.2mg",
    "name": "Sea Strike",
    "year": "1987",
    "type": "game",
    "desc": "\"Sea Strike\" is a 1987 action game developed by Richard L. Seaborne, Jeff A. Lefferts, and Mei-Ying Dell'Aquila, and distributed by PBI Software. It requires a 512K Apple IIgs. 由 Richard Seaborne & Jeff Lefferts 開發，PBI Software 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Sea Strike"
  },
  {
    "id": "a2gs_Sensei_1991_Miami_Software_FW",
    "emu": "apple2gs",
    "file": "Sensei_1991_Miami_Software_FW.2mg",
    "name": "Sensei",
    "year": "1991",
    "type": "game",
    "desc": "The term \"先生\", read sensei in Japanese, xiansheng in Chinese, seonsaeng in Korean, and tiên sinh in Vietnamese, is an honorific used in the Sinosphere. In Japanese, the term literally means \"person born before another\" or \"one who comes before\". It is generally used after a person's name and means \"teacher\".",
    "developer": "Phil Rivipellio, Walt Scapela & Neil Pulcadesso (Miami Software)",
    "publisher": "",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Sensei"
  },
  {
    "id": "wozaday_Serve_and_Volley_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0750_Serve_Volley/0750_Serve__Volley.po",
    "name": "Serve & Volley",
    "year": "1988",
    "type": "game",
    "desc": "\"Serve & Volley\" is a 1988 sports game developed by Rick Banks, Paul Butler, Ken Shimizu, Danny Chin, Paul Battersby, Jeffrey J. Sigler, Grant Campbell, and Jay Stevens, and distributed by Accolade. It requires a 512K Apple IIgs. 這是一款運動遊戲，模擬各種體育競技項目。 由 Jeffrey Sigler 開發，Accolade 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Jeffrey Sigler",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Serve & Volley"
  },
  {
    "id": "a2gs_Shadowgate_1988_Mindscape",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "file2": "Shadowgate_1988_Mindscape.2mg",
    "name": "Shadowgate",
    "year": "1988",
    "type": "game",
    "desc": "Shadowgate is a 1987 point-and-click adventure game developed by ICOM Simulations and published by Mindscape for the Macintosh as part of the MacVenture series. The game takes place in the Castle Shadowgate, residence of the evil Warlock Lord. The game was generally well-received, and was followed by several sequels and remakes for various systems.",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "screenshot": "https://archive.org/download/wozaday_Shadowgate_IIgs/00playable_screenshot.png",
    "nameCh": "影之門"
  },
  {
    "id": "wozaday_Shanghai_II_Dragons_Eye_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Shanghai II",
    "year": "1987",
    "type": "game",
    "desc": "Shanghai II: Dragon's Eye is a 1990 puzzle video game developed and published by Activision. It is a sequel to Shanghai .",
    "developer": "Manley & Associates (Brodie Lockard & Ivan Manley)",
    "publisher": "Activision",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "上海2"
  },
  {
    "id": "a2gs_Silent_Service_1987_Microprose",
    "emu": "apple2gs",
    "file": "Silent_Service_1987_Microprose.2mg",
    "name": "Silent Service",
    "year": "1987",
    "type": "game",
    "desc": "Silent Service may refer to:Royal Navy Submarine Service or Silent Service, the submarine element of the Royal Navy Silent Service, a 1985 video game The Silent Service, a 1988 Japanese manga and anime series The Silent Service, a 1944 nonfiction book by Ion Idriess The Silent Service, a series of books by H. Jay Riker",
    "developer": "Ed Magnin",
    "publisher": "Microprose",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Silent Service"
  },
  {
    "id": "wozaday_Silpheed_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_0644_Silpheed_Disk_1/0644_Silpheed_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_0645_Silpheed_Disk_2/0645_Silpheed_Disk_2.po",
    "name": "Silpheed",
    "year": "1989",
    "type": "game",
    "desc": "Silpheed is a video game developed by Game Arts and designed by Takeshi Miyaji. It made its debut on the Japanese PC-8801 in 1986, and was ported to the FM-7 and MS-DOS soon after. It was later remade for the Sega CD and has a sequel called Silpheed: The Lost Planet for the PlayStation 2.",
    "developer": "Game Arts",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "銀河戰機"
  },
  {
    "id": "wozaday_Sinbad_and_the_Throne_of_the_Falcon",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "name": "Sinbad and the Throne of the Falcon",
    "year": "1990",
    "type": "game",
    "desc": "Sinbad and the Throne of the Falcon is a 1987 action-adventure game developed and published by Cinemaware. Set in an Arabian Nights-esque world, the player assumes the role of Sinbad the Sailor, and is commissioned by The Princess to rid the land of the Dark Prince. The game was designed and programmed by Bill Williams for the Amiga, who also wrote Mind Walker.",
    "developer": "Jim Simmons & Andrew Caldwell",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "辛巴達與獵鷹王座"
  },
  {
    "id": "wozaday_Skate_or_Die_v10_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Skate or Die!",
    "year": "1988",
    "type": "game",
    "desc": "Skate or Die! is a skateboarding video game released by Electronic Arts in 1987 for the Commodore 64. It is EA's first internally developed game. Versions for the Apple IIGS, MS-DOS, Amstrad CPC, and ZX Spectrum followed. It was ported to the Nintendo Entertainment System by Konami, published under the company's Ultra Games branding.",
    "developer": "David Bunch, Michael Kosaka & Michelle Shelfer",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "滑板生死戰"
  },
  {
    "id": "a2gs_Solarian_1992_Coloreez_SW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Solarian",
    "year": "1992",
    "type": "game",
    "desc": "The Sun is the star at the centre of the Solar System. It is a massive, nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core, radiating the energy from its surface mainly as visible light and infrared radiation with 10% at ultraviolet energies. It is the main source of energy for life on Earth.",
    "developer": "David Tolson",
    "publisher": "",
    "file2": "Solarian_1992_Coloreez_SW.2mg",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "Solarian"
  },
  {
    "id": "wozaday_Solitaire_and_Cribbage_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Solitaire & Cribbage",
    "year": "1990",
    "type": "game",
    "desc": "\"Solitaire & Cribbage\" is a 1989 pair of games developed and distributed by Computrek. It requires an Apple IIgs with at least 256K RAM. Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "",
    "publisher": "Computrek Software",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Solitaire & Cribbage"
  },
  {
    "id": "wozaday_Solitaire_Royale_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Solitaire Royale",
    "year": "1990",
    "type": "game",
    "desc": "Solitaire Royale is a collection of solitaire games published by Spectrum HoloByte in 1987 for the Apple IIGS, MS-DOS, Macintosh, and Amiga. The eight games included are \"3 Shuffles and a Draw\", \"Pyramid\", \"Golf\", \"Corners\", \"Reno\", \"Klondike\", \"Canfield\", and \"Calculation\". There are also three children's games: \"Pairs\", \"The Wish\", and \"Concentration\".",
    "developer": "Jake Hoelter, Jody Sather & Brad Fregger",
    "publisher": "Spectrum Holobyte",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Solitaire Royale"
  },
  {
    "id": "wozaday_Space_Ace_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Space Ace",
    "year": "1990",
    "type": "game",
    "desc": "Space Ace is a LaserDisc video game produced by Bluth Group, Cinematronics and Advanced Microcomputer Systems. It was unveiled in October 1983, just four months after the Dragon's Lair game, followed by a limited release in December 1983 and a wide release on April 29, 1984. Like its predecessor, it featured film-quality animation played back from a LaserDisc.",
    "developer": "David Foster & Simon Douglas",
    "publisher": "Ready Soft",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Space Ace"
  },
  {
    "id": "a2gs_Space_Shark_1990_Toolbox",
    "emu": "apple2gs",
    "file": "Space_Shark_1990_Toolbox.2mg",
    "name": "Space Shark",
    "year": "1990",
    "type": "game",
    "desc": "Apple IIgs: Space Shark (1990)(Toolbox) 由 Miami Software 開發，Toolbox 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Miami Software",
    "publisher": "Toolbox",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Space Shark"
  },
  {
    "id": "wozaday_Star_Saga_One_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Star_Saga_One_Beyond_the_Boundary_1988_MasterPlay/Star_Saga_One_Beyond_the_Boundary_1988_MasterPlay.2mg",
    "name": "Star Saga One: Beyond the Boundary",
    "year": "1988",
    "type": "game",
    "desc": "Star Saga One: Beyond the Boundary is the first game in the Star Saga series. It was published in 1988 by Masterplay.",
    "developer": "Richard Dutton, Walter Freitag, Andrew Greenberg, Michael Massimilla",
    "publisher": "Master Play",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Star Saga One: Beyond the Boundary"
  },
  {
    "id": "wozaday_Star_Saga_Two_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Star_Saga_Two_The_Clathran_Menance_v1.0_1988_MasterPlay/Star_Saga_Two_The_Clathran_Menance_v1.0_1988_MasterPlay.2mg",
    "name": "Star Saga: Two - The Clathran Menace",
    "year": "1988",
    "type": "game",
    "desc": "Star Saga: Two - The Clathran Menace is a video game, the second in the Star Saga series, released in 1989 by Masterplay Publishing for Apple II, Apple IIGS, and MS-DOS.",
    "developer": "Richard Dutton, Walter Freitag, A. & S. Greenberg, Michael Massimilla, Gerald Seixas",
    "publisher": "Master Play",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Star Saga: Two - The Clathran Menace"
  },
  {
    "id": "wozaday_Sub_Battle_Simulator_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Sub Battle Simulator",
    "year": "1987",
    "type": "game",
    "desc": "Sub Battle Simulator is a naval combat simulation game released by Epyx in 1987. The game was developed by Digital Illusions, Inc. It was released for the Amiga, Apple IIGS, Commodore 64, Atari ST, Macintosh, MS-DOS, and the Tandy Color Computer 3.",
    "developer": "Rob Brannon & Kelly Fergason",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Sub Battle Simulator"
  },
  {
    "id": "wozaday_Superstar_Ice_Hockey_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Superstar Ice Hockey",
    "year": "1988",
    "type": "game",
    "desc": "Superstar Ice Hockey is a sports video game published by Mindscape in 1987.",
    "developer": "DesignStar Consultants (Andrew Caldwell)",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Superstar Ice Hockey"
  },
  {
    "id": "wozaday_Tarot_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tarot",
    "year": "1990",
    "type": "game",
    "desc": "Tarot is a set of playing cards used in tarot games and in fortune-telling or divination. From at least the mid-15th century, the tarot was used to play trick-taking card games such as Tarocchini. From their Italian roots, tarot games spread to most of Europe, evolving into new forms including German Grosstarok and modern examples such as French Tarot and Austrian Königrufen.",
    "developer": "François Uhrich & Jean-François Sauvage",
    "publisher": "Toolbox",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Tarot"
  },
  {
    "id": "wozaday_Task_Force_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Task Force",
    "year": "1990",
    "type": "game",
    "desc": "A task force is a unit or formation established to work on a single defined task or activity. Originally introduced by the United States Navy, the term has now caught on for general usage and is a standard part of NATO terminology. Many non-military organizations now create \"task forces\" or task groups for temporary activities that might have once been performed by ad hoc committees.",
    "developer": "Visual Concepts (Scott Patterson & Matt Crysdale)",
    "publisher": "Britannica / Fanfare",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Task Force"
  },
  {
    "id": "wozaday_Tass_Times_in_Tonetown_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tass Times in Tonetown",
    "year": "1986",
    "type": "game",
    "desc": "Tass Times in Tonetown is an adventure game published by Activision in 1986. It was designed by Michael Berlyn and Muffy McClung Berlyn and programmed by Rebecca Heineman of Interplay in cooperation with Brainwave Creations.",
    "developer": "Rebecca Heineman (Interplay Productions & Brainwave Creations)",
    "publisher": "Activision",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Tass Times in Tonetown"
  },
  {
    "id": "a2gs_Tetris_1988_Spectrum_Holobyte",
    "emu": "apple2gs",
    "file": "Tetris_1988_Spectrum_Holobyte.2mg",
    "name": "Tetris",
    "year": "1988",
    "type": "game",
    "desc": "Tetris is a puzzle video game created by Alexey Pajitnov, a Soviet software engineer. In typical Tetris gameplay, falling tetromino shapes must be neatly sorted into a pile. Once a horizontal line of the game board is filled in, it disappears, granting points and preventing the pile from overflowing.",
    "developer": "Roland Gustafsson, Sean Barger & Dan Geisler",
    "publisher": "Spectrum Holobyte",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "俄羅斯方塊"
  },
  {
    "id": "wozaday_Thexder_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/a2gs_Thexder_1987_Sierra/Thexder_1987_Sierra.2mg",
    "name": "Thexder",
    "year": "1987",
    "type": "game",
    "desc": "Thexder is a run and gun video game from Game Arts, originally released for the NEC PC-8801 in 1985. It was ported to many systems, including the Famicom, MSX, Apple II, and MS-DOS. It was a commercial success, selling over one million units worldwide.",
    "developer": "Game Arts",
    "publisher": "Sierra",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "機甲戰士"
  },
  {
    "id": "wozaday_The_Third_Courier_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Third Courier, The",
    "year": "1989",
    "type": "game",
    "desc": "The Third Courier is a 1989 video game developed by Manley & Associates and published by Accolade.",
    "developer": "Manley & Associates",
    "publisher": "Accolade",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Third Courier, The"
  },
  {
    "id": "wozaday_The_Three_Stooges_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "name": "Three Stooges, The",
    "year": "1990",
    "type": "game",
    "desc": "The Three Stooges were an American vaudeville and comedy troupe active from 1922 until 1970, best remembered for their 190 short-subject films by Columbia Pictures. Their hallmark styles were physical, farce, and slapstick comedy. Six Stooges appeared over the act's run. The two constants were:Moe Howard, 1922–1975, and Larry Fine, 1925–1970",
    "developer": "Ed Magnin",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "三個活寶"
  },
  {
    "id": "a2gs_Tinies_The_1994_Brutal_Deluxe_FW",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Tinies, The",
    "year": "1994",
    "type": "game",
    "desc": "The Brainies is a puzzle video game released on the Super Nintendo Entertainment System console and Atari ST, Amiga, Apple IIgs, Macintosh, and Amstrad CPC computers. Even though its European title is Tiny Skweeks, the connection to the popular Skweek series was made late. The game is also known as The Tinies on home computers.",
    "developer": "Antoine Vignau & Olivier Zardini (Brutal Deluxe)",
    "publisher": "",
    "file2": "Tinies_The_1994_Brutal_Deluxe_FW.2mg",
    "screenshot": "00_coverscreenshot.png",
    "nameCh": "Tinies, The"
  },
  {
    "id": "wozaday_Tomahawk_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tomahawk",
    "year": "1988",
    "type": "game",
    "desc": "A tomahawk is a type of single-handed axe used by the many Indigenous peoples and nations of North America. It traditionally resembles a hatchet with a straight shaft.",
    "developer": "John Brooks",
    "publisher": "Datasoft",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Tomahawk"
  },
  {
    "id": "wozaday_The_Tower_of_Myraglen_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Tower of Myraglen",
    "year": "1987",
    "type": "game",
    "desc": "Tower of Myraglen is an adventure role-playing video game published by PBI Software. It was released for the Apple IIGS in 1987.",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Tower of Myraglen"
  },
  {
    "id": "wozaday_Transylvania_III_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Transylvania III",
    "year": "1990",
    "type": "game",
    "desc": "\"Transylvania III\" is a 1991 adventure game developed by Antonio Antiochia and Veronika Slintak, and distributed by Polarware. It runs on any Apple IIgs. 這是一款冒險遊戲，玩家需要探索世界、解決謎題並推進劇情。 由 Antonio Antiochia & Veronika Slintak 開發，Polarware 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 後期的優秀作品。",
    "developer": "Antonio Antiochia & Veronika Slintak",
    "publisher": "Polarware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Transylvania III"
  },
  {
    "id": "a2gs_Triango_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Triango_1988_California_Dreams.2mg",
    "name": "Triango",
    "year": "1988",
    "type": "game",
    "desc": "\"TrianGo\" is a 1988 board game developed by Staszek Bartkowski, Marcin Szostakowski, Maciej Markuszewski, Dorota Błaszczak, and distributed by California Dreams. It requires a 512K Apple IIgs. 這是一款棋類遊戲，電子化的傳統棋盤遊戲。 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "https://archive.org/download/wozaday_TrianGo_IIgs/00playable_screenshot.png",
    "nameCh": "Triango"
  },
  {
    "id": "a2gs_Tunnels_of_Armageddon_1990_California_Dreams",
    "emu": "apple2gs",
    "file": "Tunnels_of_Armageddon_1990_California_Dreams.2mg",
    "name": "Tunnels of Armageddon",
    "year": "1990",
    "type": "game",
    "desc": "Tunnels of Armageddon is a computer game involving racing and shooting while avoiding obstacles.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Tunnels of Armageddon"
  },
  {
    "id": "wozaday_Uninvited_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "name": "Uninvited",
    "year": "1988",
    "type": "game",
    "desc": "Uninvited or The Uninvited may refer to:",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "不速之客"
  },
  {
    "id": "e2gs_0528_Vegas_Craps_v1.0",
    "emu": "apple2gs",
    "file": "0528_Vegas_Craps_v1.0.po",
    "name": "Vegas Craps",
    "year": "1988",
    "type": "game",
    "desc": "Apple IIgs: Vegas Craps (1988)(California Dreams) 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Vegas Craps"
  },
  {
    "id": "a2gs_Vegas_Gambler_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Vegas_Gambler_1988_California_Dreams.2mg",
    "name": "Vegas Gambler",
    "year": "1988",
    "type": "game",
    "desc": "\"Vegas Gambler\" is a 1988 simulation game developed by Marek Jackiewicz, Andrzej Miciłkiewicz, Marcin Szostakowski, Maciej Markuszewski, and Dorota Błaszczak, and distributed by California Dreams. It requires a 512K Apple IIgs. 由 Logical Design Works 開發，California Dreams 發行。 Apple IIgs 版本擁有增強的 16 位元圖形和立體聲音效。 這是 Apple IIgs 黃金時代的經典作品之一。",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Vegas Gambler"
  },
  {
    "id": "wozaday_War_in_Middle_Earth_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "War in Middle Earth",
    "year": "1989",
    "type": "game",
    "desc": "War in Middle Earth is a real-time strategy game released for the ZX Spectrum, MSX, Commodore 64, Amstrad CPC, MS-DOS, Amiga, Apple IIGS, and Atari ST in 1988 by Virgin Mastertronic on the Melbourne House label.",
    "developer": "Synergistic Software",
    "publisher": "Melbourne House",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "War in Middle Earth"
  },
  {
    "id": "wozaday_Windwalker_IIgs",
    "emu": "apple2gs",
    "file": "https://archive.org/download/e2gs_1171_Windwalker_Disk_1/1171_Windwalker_Disk_1.po",
    "file2": "https://archive.org/download/e2gs_1172_Windwalker_Disk_2/1172_Windwalker_Disk_2.po",
    "name": "Windwalker",
    "year": "1990",
    "type": "game",
    "desc": "Windwalker may refer to:The Wind-Walker, an epithet for Ithaqua, in the Cthulhu mythos stories Windwalker, a 1981 film starring Trevor Howard and Nick Ramus Windwalker, a band from Vancouver, British Columbia Windwalker, a sequel to the RPG adventure game, Moebius: The Orb of Celestial Harmony, published by Origin Systems Windwalker, a 2003 fantasy novel by Elaine Cunningham Windwalkers,.",
    "developer": "Greg Malone",
    "publisher": "Origin",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Windwalker"
  },
  {
    "id": "wozaday_Winter_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Winter Games",
    "year": "1987",
    "type": "game",
    "desc": "Winter Games is a 1985 sports video game developed by Epyx and released in Europe by U.S. Gold. A snow-and-ice themed follow-up to the highly successful Summer Games, Winter Games was released in 1985 for the Commodore 64 and later ported to several popular home computers and video game consoles of the 1980s.",
    "developer": "Westwood & IT",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "冬季運動會"
  },
  {
    "id": "a2gs_Wolfenstein_3D_v1.1_1997_Logicware_FW",
    "emu": "apple2gs",
    "file": "00_DualBootHelper_qkumba.dsk",
    "name": "Wolfenstein 3D",
    "year": "1998",
    "type": "game",
    "desc": "Wolfenstein 3D is a 1992 first-person shooter game developed by id Software and published by Apogee Software and FormGen for DOS. It was inspired by the 1981 Muse Software video game Castle Wolfenstein, and is the third installment in the Wolfenstein series.",
    "developer": "Rebecca Heineman, Eric Shepherd & NinjaForce",
    "publisher": "Logicware",
    "file2": "Wolfenstein_3D_v1.1_1997_Logicware_FW.2mg",
    "screenshot": "00_coverscreenshot.jpg",
    "nameCh": "Wolfenstein 3D"
  },
  {
    "id": "wozaday_World_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "World Games",
    "year": "1987",
    "type": "game",
    "desc": "The World Games are an international multi-sport event comprising sports and sporting disciplines that are not contested in the Olympic Games. They are usually held every four years, one year after a Summer Olympic Games, over the course of 11 days. The World Games are governed by the International World Games Association, under the patronage of the International Olympic Committee.",
    "developer": "Westwood & IT",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "世界運動會"
  },
  {
    "id": "wozaday_World_Tour_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "World Tour Golf",
    "year": "1987",
    "type": "game",
    "desc": "World Tour Golf is a sports video game by Evan Robinson, Nicky Robinson, and Paul Reiche III which was published by Electronic Arts in 1986 for Commodore 64, Amiga, Apple IIGS, and MS-DOS.",
    "developer": "John Selhorst & Tanager Software Productions",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "World Tour Golf"
  },
  {
    "id": "wozaday_Xenocide_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Xenocide",
    "year": "1989",
    "type": "game",
    "desc": "Xenocide is the third book in the Ender's Game series, a science fiction series by the American author Orson Scott Card. It was first published during a period of increasing globalization and heightened awareness of cultural differences, and the writing reflects this in its techniques, mood, and emotive effect on the reader.",
    "developer": "Pangea Software",
    "publisher": "Micro Revelations",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Xenocide"
  },
  {
    "id": "wozaday_Zany_Golf",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Zany Golf",
    "year": "1988",
    "type": "game",
    "desc": "Zany Golf, also known as Will Harvey's Zany Golf, is a fantasy take on miniature golf developed by Sandcastle Productions and published by Electronic Arts in 1988. The game was originally written for the Apple IIGS and subsequently ported to the Amiga, Atari ST, and MS-DOS compatible operating systems. In 1990, a port was released for the Sega Genesis.",
    "developer": "Sandcastle (Will Harvey, Ian Nitchal & Doug Fulton)",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "瘋狂高爾夫"
  },
  {
    "id": "wozaday_Where_in_the_USA_is_Carmen_Sandiego_800K",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Where in the USA is Carmen Sandiego?",
    "year": "1990",
    "type": "edu",
    "desc": "Where in the U.S.A. Is Carmen Sandiego? may refer to:Where in the U.S.A. Is Carmen Sandiego? Where in the U.S.A. Is Carmen Sandiego? Deluxe, a 1992 video game Where in the U.S.A. Is Carmen Sandiego? Where in America is Carmen Sandiego?: The Great Amtrak Train Adventure, a 1998 video game",
    "developer": "Sculptured Software (Peter Adams)",
    "publisher": "Broderbund",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Where in the USA is Carmen Sandiego?"
  },
  {
    "id": "wozaday_Where_in_the_World_is_Carmen_Sandiego_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Where in the World is Carmen Sandiego?",
    "year": "1989",
    "type": "edu",
    "desc": "Where in the World Is Carmen Sandiego? may refer to:Carmen Sandiego, a media franchise sometimes referred to as Where in the World Is Carmen Sandiego? Carmen Sandiego, several of which are titled Where in the World Is Carmen Sandiego? Deluxe, a 1992 video game Where in the World Is Carmen Sandiego?, partially based on the television game show Where in the World Is Carmen Sandiego?",
    "developer": "Loring Vogel",
    "publisher": "Broderbund",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "nameCh": "Where in the World is Carmen Sandiego?"
  }
];