/**
 * Apple IIgs 遊戲庫
 * 生成時間: 2025/12/18 下午9:21:01
 * 遊戲數量: 70
 */

window.games = [
  {
    "id": "wozaday_4th_and_Inches_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "4th & Inches IIgs",
    "nameEn": "4th & Inches IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"4th & Inches\" is a 1988 sports game developed by Tony Manso & Sculptured Software and published by Accolade. It requires an Apple IIgs.",
    "developer": "Tony Manso & Sculptured Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Airball_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Airball IIgs",
    "nameEn": "Airball IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Airball\" is a 1989 action game developed by Jason Harper and published by MicroDeal. It requires an Apple IIgs.",
    "developer": "Jason Harper",
    "publisher": "MicroDeal",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Alien_Mind",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Alien Mind",
    "nameEn": "Alien Mind",
    "year": "1988",
    "type": "game",
    "desc": "\"Alien Mind\" is a 1988 action-adventure game developed by Rob Karr & Matt Crysdale and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Rob Karr & Matt Crysdale",
    "publisher": "PBI Software",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Ancient_Glory_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Ancient Glory IIgs",
    "nameEn": "Ancient Glory IIgs",
    "year": "1993",
    "type": "game",
    "desc": "\"Ancient Glory\" is a 1993 action game developed by Logical Design Works, Westwood Associates and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Logical Design Works, Westwood Associates",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Arkanoid_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Arkanoid II: Revenge of Doh IIgs",
    "nameEn": "Arkanoid II: Revenge of Doh IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Arkanoid\" is a 1988 action game developed by Ryan Ridges & John Lund and published by Taito America. It requires an Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Arkanoid_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Arkanoid II: Revenge of Doh IIgs",
    "nameEn": "Arkanoid II: Revenge of Doh IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Arkanoid II: Revenge of Doh\" is a 1989 action game developed by Ryan Ridges & John Lund and published by Taito America. It requires an Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Balance_of_Power_1990_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Balance of Power: The 1990 Edition IIgs",
    "nameEn": "Balance of Power: The 1990 Edition IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Balance of Power: The 1990 Edition\" is a 1989 simulation game developed by Chris Crawford and published by Mindscape. It requires an Apple IIgs.",
    "developer": "Chris Crawford",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Battle_Chess_1989_Interplay",
    "emu": "apple2gs",
    "file": "Battle_Chess_1989_Interplay.2mg",
    "name": "Battle Chess IIgs",
    "nameEn": "Battle Chess IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Battle Chess\" is a 1989 board game developed by Rebecca Heineman and published by Interplay Productions. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_The_Black_Cauldron_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Black Cauldron IIgs",
    "nameEn": "The Black Cauldron IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Black Cauldron\" is a 1987 adventure game developed by Al Lowe and published by Sierra. It requires an Apple IIgs.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Blackjack_Academy_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Blackjack Academy IIgs",
    "nameEn": "Blackjack Academy IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Blackjack Academy\" is a 1988 cards game developed by Westwood and published by Micro Illusions. It requires an Apple IIgs.",
    "developer": "Westwood",
    "publisher": "Micro Illusions",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Blockout_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Block Out IIgs",
    "nameEn": "Block Out IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Block Out\" is a 1989 puzzle game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Bridge_6_0_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Bridge 6.0 IIgs",
    "nameEn": "Bridge 6.0 IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Bridge 6.0\" is a 1989 cards game developed by Arthur Walsh & Roger Harnish and published by Artworx. It requires an Apple IIgs.",
    "developer": "Arthur Walsh & Roger Harnish",
    "publisher": "Artworx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Bubble_Ghost_1988_Accolade",
    "emu": "apple2gs",
    "file": "Bubble_Ghost_1988_Accolade.2mg",
    "name": "Bubble Ghost IIgs",
    "nameEn": "Bubble Ghost IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Bubble Ghost\" is a 1988 action game developed by ERE Informatique and published by Accolade. It requires an Apple IIgs.",
    "developer": "ERE Informatique",
    "publisher": "Accolade",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "wozaday_Invisible_Bugs_800K",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Invisible Bugs",
    "nameEn": "Invisible Bugs",
    "year": "2021",
    "type": "game",
    "desc": "\"BuGS\" is a 2021 shoot 'em up game developed by Jeremy Rand and published by . It requires an Apple IIgs.",
    "developer": "Jeremy Rand",
    "publisher": "",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_California_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "California Games IIgs",
    "nameEn": "California Games IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"California Games\" is a 1988 sports game developed by Designer Software (Jimmy Huey) and published by Epyx. It requires an Apple IIgs.",
    "developer": "Designer Software (Jimmy Huey)",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Captain_Blood_1989_Mindscape",
    "emu": "apple2gs",
    "file": "Captain_Blood_1989_Mindscape.2mg",
    "name": "Captain Blood IIgs",
    "nameEn": "Captain Blood IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Captain Blood\" is a 1989 simulation/adventure game developed by ERE Informatique (Alexis Martial & Jean-Michel Jarre) and published by Mindscape. It requires an Apple IIgs.",
    "developer": "ERE Informatique (Alexis Martial & Jean-Michel Jarre)",
    "publisher": "Mindscape",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Cavern_Cobra_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Cavern Cobra IIgs",
    "nameEn": "Cavern Cobra IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Cavern Cobra\" is a 1987 shoot 'em up game developed by Greg Hale and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Greg Hale",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Fidelity_Chessmaster_2100_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Fidelity Chessmaster 2100 IIgs",
    "nameEn": "The Fidelity Chessmaster 2100 IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Chessmaster 2100, The Fidelity\" is a 1988 board game developed by Troy Heere & Mark Manyen and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "Troy Heere & Mark Manyen",
    "publisher": "Software Toolworks",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Club_Backgammon_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Club Backgammon IIgs",
    "nameEn": "Club Backgammon IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Club Backgammon\" is a 1988 board game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Columns_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Columns GS",
    "nameEn": "Columns GS",
    "year": "1991",
    "type": "game",
    "desc": "\"Columns\" is a 1991 puzzle game developed by Kenrick Mock (Sound Barrier Systems) and published by . It requires an Apple IIgs.",
    "developer": "Kenrick Mock (Sound Barrier Systems)",
    "publisher": "",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Cribbage_Gin_King_1990_The_Software_Toolworks",
    "emu": "apple2gs",
    "file": "SystemDisk.2mg",
    "name": "Gin King / Cribbage King IIgs",
    "nameEn": "Gin King / Cribbage King IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Cribbage King / Gin King\" is a 1990 cards game developed by Mark Manyen and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "Mark Manyen",
    "publisher": "Software Toolworks",
    "file2": "Cribbage__Gin_King_1990_The_Software_Toolworks.2mg",
    "screenshot": "00_coverscreenshot.png"
  },
  {
    "id": "a2gs_Crystal_Quest_1989_Cassidy_Greene",
    "emu": "apple2gs",
    "file": "Crystal_Quest_1989_Cassidy__Greene.2mg",
    "name": "Crystal Quest IIgs",
    "nameEn": "Crystal Quest IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Crystal Quest\" is a 1989 action game developed by Rebecca Heineman and published by Cassidy & Greene. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Cassidy & Greene",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Dark_Castle_1989_09_22_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dark Castle 1989-09-22 IIgs",
    "nameEn": "Dark Castle 1989-09-22 IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Dark Castle\" is a 1989 action game developed by Lane Roath and published by Three Sixty. It requires an Apple IIgs.",
    "developer": "Lane Roath",
    "publisher": "Three Sixty",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Defender_of_the_Crown_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "Defender of the Crown IIgs (woz-a-day collection).zip/Defender of the Crown IIgs (woz-a-day collection)/Defender of the Crown IIgs - Reel 2.woz",
    "name": "Defender of the Crown IIgs",
    "nameEn": "Defender of the Crown IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Defender of the Crown\" is a 1989 action/strategy game developed by Manley & Associates and published by Cinemaware. It requires an Apple IIgs.",
    "developer": "Manley & Associates",
    "publisher": "Cinemaware",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Deja_Vu_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Déjà Vu II: Lost in Las Vegas IIgs",
    "nameEn": "Déjà Vu II: Lost in Las Vegas IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Deja Vu II: Lost in Las Vegas\" is a 1989 adventure game developed by ICOM Simulations and published by Mindscape. It requires an Apple IIgs.",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Destroyer_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Destroyer IIgs",
    "nameEn": "Destroyer IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Destroyer\" is a 1987 simulation game developed by Michael Kosaka & Chuck Sommerville and published by Epyx. It requires an Apple IIgs.",
    "developer": "Michael Kosaka & Chuck Sommerville",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Downhill_Challenge_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Downhill Challenge IIgs",
    "nameEn": "Downhill Challenge IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Downhill Challenge\" is a 1989 sports game developed by Microids and published by Broderbund. It requires an Apple IIgs.",
    "developer": "Microids",
    "publisher": "Broderbund",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Dragon_Wars_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dragon Wars IIgs",
    "nameEn": "Dragon Wars IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Dragon Wars\" is a 1990 rpg game developed by Rebecca Heineman and published by Interplay Productions. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Dream_Zone_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Dream Zone IIgs",
    "nameEn": "Dream Zone IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Dream Zone\" is a 1988 adventure game developed by Naughty Dog (Andy Gavin & Jason Rubin) and published by Baudville. It requires an Apple IIgs.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Baudville",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Fast_Break_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Fast Break IIgs",
    "nameEn": "Fast Break IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Fast Break\" is a 1989 sports game developed by Greg Hospelhorn & George Wong and published by Accolade. It requires an Apple IIgs.",
    "developer": "Greg Hospelhorn & George Wong",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Final_Assault_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Final Assault IIgs",
    "nameEn": "Final Assault IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Final Assault\" is a 1988 simulation game developed by Infogrames and published by Epyx. It requires an Apple IIgs.",
    "developer": "Infogrames",
    "publisher": "Epyx",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Full_Metal_Planete_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Full Metal Planete IIgs",
    "nameEn": "Full Metal Planete IIgs",
    "year": "1993",
    "type": "game",
    "desc": "\"Full Metal Planete\" is a 1993 turn-based strategy game developed by Brainstorm Software (Francois Uhrich & Nicolas Bergeret) and published by Infogrames. It requires an Apple IIgs.",
    "developer": "Brainstorm Software (Francois Uhrich & Nicolas Bergeret)",
    "publisher": "Infogrames",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_GATE_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "GATE IIgs",
    "nameEn": "GATE IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"GATE\" is a 1991 action-adventure game developed by Bright Software (Joerg Kienzle, Yann Le Tensorer & Henrik Gudat) and published by Toolbox & Seven Hills. It requires an Apple IIgs.",
    "developer": "Bright Software (Joerg Kienzle, Yann Le Tensorer & Henrik Gudat)",
    "publisher": "Toolbox & Seven Hills",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Gauntlet_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gauntlet IIgs",
    "nameEn": "Gauntlet IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Gauntlet\" is a 1988 action game developed by Atari Games and published by Mindscape. It requires an Apple IIgs.",
    "developer": "Atari Games",
    "publisher": "Mindscape",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Gnarly_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Gnarly Golf IIgs",
    "nameEn": "Gnarly Golf IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Gnarly Golf\" is a 1989 sports game developed by Visual Concepts (Jim Coliz Jnr & Darren Bartlett) and published by Britannica / Fanfare. It requires an Apple IIgs.",
    "developer": "Visual Concepts (Jim Coliz Jnr & Darren Bartlett)",
    "publisher": "Britannica / Fanfare",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Grand_Prix_Circuit_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Grand Prix Circuit IIgs",
    "nameEn": "Grand Prix Circuit IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Grand Prix Circuit\" is a 1989 racing game developed by Distinctive Software and published by Accolade. It requires an Apple IIgs.",
    "developer": "Distinctive Software",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Halls_of_Montezuma_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Halls of Montezuma IIgs",
    "nameEn": "Halls of Montezuma IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Halls of Montezuma\" is a 1990 turn-based strategy game developed by Roger Keating & Ian Trout and published by Strategic Studies Group. It requires an Apple IIgs.",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Hardball_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Hardball! IIgs",
    "nameEn": "Hardball! IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"HardBall!\" is a 1987 sports game developed by Distinctive Software (Dan Thompson) and published by Accolade. It requires an Apple IIgs.",
    "developer": "Distinctive Software (Dan Thompson)",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Hover_Blade_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "Hover Blade IIgs (woz-a-day collection)/Hover Blade IIgs - Disk 2.woz",
    "name": "Hover Blade IIgs",
    "nameEn": "Hover Blade IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"Hover Blade\" is a 1991 action game developed by Shiraz Akmal & Eric Boden and published by MCX. It requires an Apple IIgs.",
    "developer": "Shiraz Akmal & Eric Boden",
    "publisher": "MCX",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Hunt_for_Red_October_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Hunt for Red October IIgs",
    "nameEn": "The Hunt for Red October IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Hunt for Red October\" is a 1989 simulation game developed by John Brooks, Todd Daugherty & Alex Villagran and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "John Brooks, Todd Daugherty & Alex Villagran",
    "publisher": "Software Toolworks",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Immortal_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Immortal IIgs",
    "nameEn": "The Immortal IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Immortal, The\" is a 1990 action rpg game developed by Sandcastle (Will Harvey, Ian Nitchal & Doug Fulton) and published by Electronic Arts. It requires an Apple IIgs.",
    "developer": "Sandcastle (Will Harvey, Ian Nitchal & Doug Fulton)",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Jack_Nicklaus_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Jack Nicklaus' Greatest 18 Holes of Major Championship Golf IIgs",
    "nameEn": "Jack Nicklaus' Greatest 18 Holes of Major Championship Golf IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Jack Nicklaus' Greatest 18 Holes of Major Championship Golf\" is a 1989 sports game developed by Tony Manso and published by Accolade. It requires an Apple IIgs.",
    "developer": "Tony Manso",
    "publisher": "Accolade",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_King_of_Chicago_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The King of Chicago IIgs",
    "nameEn": "The King of Chicago IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"King of Chicago\" is a 1989 action/strategy game developed by Doug Sharp and published by Cinemaware. It requires an Apple IIgs.",
    "developer": "Doug Sharp",
    "publisher": "Cinemaware",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Last_Ninja_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Last Ninja IIgs",
    "nameEn": "The Last Ninja IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Last Ninja, The\" is a 1988 action-adventure game developed by System 3 and published by Activision. It requires an Apple IIgs.",
    "developer": "System 3",
    "publisher": "Activision",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Leisure_Suit_Larry_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Leisure Suit Larry in the Land of the Lounge Lizards IIgs",
    "nameEn": "Leisure Suit Larry in the Land of the Lounge Lizards IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Leisure Suit Larry in the Land of the Lounge Lizards\" is a 1987 adventure game developed by Al Lowe and published by Sierra. It requires an Apple IIgs.",
    "developer": "Al Lowe",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Life_and_Death_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Life and Death IIgs",
    "nameEn": "Life and Death IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Life & Death\" is a 1989 simulation game developed by Mark Manyen & Jacob P. Smith and published by Software Toolworks. It requires an Apple IIgs.",
    "developer": "Mark Manyen & Jacob P. Smith",
    "publisher": "Software Toolworks",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_The_Lost_Tribe_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "The Lost Tribe v1.0 IIgs",
    "nameEn": "The Lost Tribe v1.0 IIgs",
    "year": "1992",
    "type": "game",
    "desc": "\"Lost Tribe, The\" is a 1992 adventure/strategy game developed by Steve Vance, Frank Andrews & Todd Harris and published by Lawrence Productions. It requires an Apple IIgs.",
    "developer": "Steve Vance, Frank Andrews & Todd Harris",
    "publisher": "Lawrence Productions",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "a2gs_Mancala_1988_California_Dreams",
    "emu": "apple2gs",
    "file": "Mancala_1988_California_Dreams.2mg",
    "name": "Mancala IIgs",
    "nameEn": "Mancala IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mancala\" is a 1988 board game developed by Logical Design Works and published by California Dreams. It requires an Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams",
    "screenshot": "00_coverscreenshot.jpg"
  },
  {
    "id": "wozaday_Marble_Madness_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Marble Madness IIgs",
    "nameEn": "Marble Madness IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Marble Madness\" is a 1988 action game developed by Will Harvey and published by Electronic Arts. It requires an Apple IIgs.",
    "developer": "Will Harvey",
    "publisher": "Electronic Arts",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mazer_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mazer II IIgs",
    "nameEn": "Mazer II IIgs",
    "year": "1992",
    "type": "game",
    "desc": "\"Mazer II\" is a 1992 action rpg game developed by Farfetch Software and published by Big Red Computer Club. It requires an Apple IIgs.",
    "developer": "Farfetch Software",
    "publisher": "Big Red Computer Club",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mean_18_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mean 18 IIgs",
    "nameEn": "Mean 18 IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Mean 18\" is a 1987 sports game developed by Mark Lesser & Micro Smiths and published by Accolade. It requires an Apple IIgs.",
    "developer": "Mark Lesser & Micro Smiths",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mini_Putt_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mini-Putt IIgs",
    "nameEn": "Mini-Putt IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mini-Putt\" is a 1988 sports game developed by Ross Salas & Tanager Software Productions and published by Accolade. It requires an Apple IIgs.",
    "developer": "Ross Salas & Tanager Software Productions",
    "publisher": "Accolade",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Mixed_Up_Mother_Goose_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Mixed-Up Mother Goose IIgs",
    "nameEn": "Mixed-Up Mother Goose IIgs",
    "year": "1988",
    "type": "game",
    "desc": "\"Mixed Up Mother Goose\" is a 1988 adventure game developed by Roberta Williams and published by Sierra. It requires an Apple IIgs.",
    "developer": "Roberta Williams",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Monte_Carlo_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Monte Carlo IIgs",
    "nameEn": "Monte Carlo IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Monte Carlo\" is a 1987 gambling game developed by Richard Seaborne & Jeff Lefferts and published by PBI Software. It requires an Apple IIgs.",
    "developer": "Richard Seaborne & Jeff Lefferts",
    "publisher": "PBI Software",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Neuromancer_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Neuromancer IIgs",
    "nameEn": "Neuromancer IIgs",
    "year": "1989",
    "type": "game",
    "desc": "\"Neuromancer\" is a 1989 adventure game developed by Rebecca Heineman and published by Interplay Productions. It requires an Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Omega_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Omega IIgs",
    "nameEn": "Omega IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Omega\" is a 1990 simulation game developed by Micro Magic and published by Origin. It requires an Apple IIgs.",
    "developer": "Micro Magic",
    "publisher": "Origin",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Panzer_Battles_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Panzer Battles IIgs",
    "nameEn": "Panzer Battles IIgs",
    "year": "1991",
    "type": "game",
    "desc": "\"Panzer Battles\" is a 1991 turn-based strategy game developed by Roger Keating, Danny Stevens & Ian Trout and published by Strategic Studies Group. It requires an Apple IIgs.",
    "developer": "Roger Keating, Danny Stevens & Ian Trout",
    "publisher": "Strategic Studies Group",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Pipe_Dream_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Pipe Dream IIgs",
    "nameEn": "Pipe Dream IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Pipe Dream\" is a 1990 puzzle game developed by Visual Concepts and published by Lucasfilm Games. It requires an Apple IIgs.",
    "developer": "Visual Concepts",
    "publisher": "Lucasfilm Games",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Police_Quest_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Police Quest IIgs",
    "nameEn": "Police Quest IIgs",
    "year": "1987",
    "type": "game",
    "desc": "\"Police Quest\" is a 1987 adventure game developed by Jim Walls and published by Sierra. It requires an Apple IIgs.",
    "developer": "Jim Walls",
    "publisher": "Sierra",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png"
  },
  {
    "id": "wozaday_Qix_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "name": "Qix IIgs",
    "nameEn": "Qix IIgs",
    "year": "1990",
    "type": "game",
    "desc": "\"Qix\" is a 1990 action game developed by Ryan Ridges & John Lund and published by Taito America. It requires an Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America",
    "screenshot": "00playable_screenshot.png"
  }
];
