window.games = [
  {
    "id": "wozaday_Ancient_Glory_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Ancient Glory",
    "nameEn": "Ancient Glory",
    "year": "1993",
    "type": "game",
    "desc": "\"Ancient Glory\" is a 1990 action game developed by Logical Design Works and distributed by California Dreams. It requires an Apple IIgs with at least 1MB RAM.",
    "developer": "Logical Design Works, Westwood Associates",
    "publisher": "Big Red Computer Club"
  },
  {
    "id": "wozaday_Arkanoid_IIgs",
    "emu": "apple2gsr1",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Arkanoid",
    "nameEn": "Arkanoid",
    "year": "1988",
    "type": "game",
    "desc": "\"Arkanoid\" is a 1988 action game developed by Ryan Ridges and John Lund, and distributed by Taito America. It requires a 512K Apple IIgs ROM 01.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America"
  },
  {
    "id": "wozaday_Battle_Chess_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Battle Chess",
    "nameEn": "Battle Chess",
    "year": "1989",
    "type": "game",
    "desc": "<p>\"Battle Chess\" is a 1989 board game developed by Jim Sproul, Todd J. Camasta, Bruce Schlickbernd, Kurt Heiden, Bill (Weez) Dugan, Thomas R. Decker, Troy P. Worrell, Michael Quarles, Rebecca Heineman, and Alan Pavlish, and distributed by Interplay. It requires a 512K Apple IIgs.</p><p><a href=\"/details/Battle_Chess_Manual\" rel=\"nofollow\">Battle Chess manual</a> contains the information you need for the copy protection questions</p>",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions"
  },
  {
    "id": "wozaday_Blackjack_Academy_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Blackjack Academy",
    "nameEn": "Blackjack Academy",
    "year": "1988",
    "type": "game",
    "desc": "\"Blackjack Academy\" is a 1987 card game developed by Dennis Saunders, PhD., Al Cheser, Allen Doum, Bob Green, Kevin Hammel, Jim Lawton, and Sandy Wardak, and distributed by MicroIllusions. It requires a 512K Apple IIgs.",
    "developer": "Westwood",
    "publisher": "Micro Illusions"
  },
  {
    "id": "wozaday_Bridge_6_0_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Bridge 6.0",
    "nameEn": "Bridge 6.0",
    "year": "1989",
    "type": "game",
    "desc": "\"Bridge 6.0\" is a 1989 board game developed by Robert Harnish and Arthur Walsh, and distributed by Artworx. This is version 2.49B. It requires a 512K Apple IIgs.",
    "developer": "Arthur Walsh & Roger Harnish",
    "publisher": "Artworx"
  },
  {
    "id": "wozaday_Bubble_Ghost_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Bubble Ghost",
    "nameEn": "Bubble Ghost",
    "year": "1988",
    "type": "game",
    "desc": "\"Bubble Ghost\" is a 1988 action game developed by Infogrames and distributed by Accolade. It requires a 512K Apple IIgs.",
    "developer": "ERE Informatique",
    "publisher": "Accolade"
  },
  {
    "id": "wozaday_California_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "California Games",
    "nameEn": "California Games",
    "year": "1988",
    "type": "game",
    "desc": "\"California Games\" is a 1988 sports game developed by Jimmy Huey, Dan Chang, Jenny Martin, Sheryl Knowles, Bill Bogenreif, Matt Householder, and Ron Fortier, and distributed by Epyx. It requires a 512K Apple IIgs.",
    "developer": "Designer Software (Jimmy Huey)",
    "publisher": "Epyx"
  },
  {
    "id": "wozaday_Club_Backgammon_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Club Backgammon",
    "nameEn": "Club Backgammon",
    "year": "1988",
    "type": "game",
    "desc": "\"Club Backgammon\" is a 1988 board game developed by Staszek Bartkowski, Jarek Olszewski, Dorota Błaszczak, Maciej Markuszewski, and Marcin Szostakowski, and distributed by California Dreams. It requires a 512K Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams"
  },
  {
    "id": "wozaday_Crystal_Quest_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Crystal Quest",
    "nameEn": "Crystal Quest",
    "year": "1989",
    "type": "game",
    "desc": "\"Crystal Quest\" is a 1989 action game developed by Patrick Buckland, Rebecca Heineman, Mike 'Jed' Patrick, and Scott Everts, and distributed by Cassidy & Greene. It requires a 512K Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Cassidy & Greene"
  },
  {
    "id": "wozaday_Dark_Castle_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Dark Castle",
    "nameEn": "Dark Castle",
    "year": "1989",
    "type": "game",
    "desc": "\"Dark Castle\" is a 1989 action game developed by Lane Roathe and distributed by Three Sixty. It requires a 768K Apple IIgs.",
    "developer": "Lane Roath",
    "publisher": "Three Sixty"
  },
  {
    "id": "wozaday_Defender_of_the_Crown_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Defender of the Crown",
    "nameEn": "Defender of the Crown",
    "year": "1989",
    "type": "game",
    "desc": "\"Defender of the Crown\" is a 1988 adventure game developed by Kellyn Beeck, James Sachs, Ivan Manley, Robert Jacob, Phyllis Jacob, Pat Cook, Jim Cuomo, Tom Warner, Jeff Hilbers, Steve Quinn, Richard La Barre, John Cutter, Rob Landeros, Doug Smith, Betsy Scafati, and Wayne Brockman, and distributed by Cinemaware Corporation. It requires a 768K Apple IIgs.",
    "developer": "Manley & Associates",
    "publisher": "Cinemaware"
  },
  {
    "id": "wozaday_Downhill_Challenge_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Downhill Challenge",
    "nameEn": "Downhill Challenge",
    "year": "1989",
    "type": "game",
    "desc": "\"Downhill Challenge\" is a 1989 sports game designed by Christian Bertrand, ported to the Apple IIgs by Jean Claude Levy, and distributed by Broderbund Software. It requires a 512K Apple IIgs.",
    "developer": "Microids",
    "publisher": "Broderbund"
  },
  {
    "id": "wozaday_Dragon_Wars_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Dragon Wars",
    "nameEn": "Dragon Wars",
    "year": "1990",
    "type": "game",
    "desc": "\"Dragon Wars\" is a 1990 roleplaying game developed by Rebecca Heineman, Todd Camasta, Charles Deenan, Brian Fargo, and Paul O'Connor, and distributed by Interplay Productions. It requires a 768K Apple IIgs.",
    "developer": "Rebecca Heineman",
    "publisher": "Interplay Productions"
  },
  {
    "id": "wozaday_Dream_Zone_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Dream Zone",
    "nameEn": "Dream Zone",
    "year": "1988",
    "type": "game",
    "desc": "\"Dream Zone\" is a 1987 adventure game developed by Andy Gavin, Jason Rubin, and Sarah Sidman, and distributed by Baudville. This is version 3.2. It requires a 512K Apple IIgs.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Baudville"
  },
  {
    "id": "wozaday_Final_Assault_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Final Assault",
    "nameEn": "Final Assault",
    "year": "1988",
    "type": "game",
    "desc": "\"Final Assault\" is a 1988 sports game developed by Infogrames and distributed by Epyx. It requires a 512K Apple IIgs.",
    "developer": "Infogrames",
    "publisher": "Epyx"
  },
  {
    "id": "wozaday_Full_Metal_Planete_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Full Metal Planete",
    "nameEn": "Full Metal Planete",
    "year": "1993",
    "type": "game",
    "desc": "\"Full Metal Planete\" is a 1990 French language board game developed by François Uhrich, Nicolas Bergeret, Louis van Proosdij Duport, Etienne Petitjean, and Pascal Wassong, and distributed by Infogrames. This is version 1.0. It requires a 1MB Apple IIgs ROM 01 or later.",
    "developer": "Brainstorm Software (Francois Uhrich & Nicolas Bergeret)",
    "publisher": "Infogrames"
  },
  {
    "id": "wozaday_Gnarly_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Gnarly Golf",
    "nameEn": "Gnarly Golf",
    "year": "1989",
    "type": "game",
    "desc": "\"Gnarly Golf\" is a 1989 sports game developed by Jim Coliz Jr., Darren Bartlett, Andy Hildebrand, and Greg Thomas, and distributed by Britannica Software. It requires a 512K Apple IIgs.",
    "developer": "Visual Concepts (Jim Coliz Jnr & Darren Bartlett)",
    "publisher": "Britannica / Fanfare"
  },
  {
    "id": "wozaday_Gold_Rush_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Gold Rush!",
    "nameEn": "Gold Rush!",
    "year": "1989",
    "type": "game",
    "desc": "\"Gold Rush!\" is a 1988 adventure game developed by Ken MacNeill, Doug MacNeill, Jeff Stephenson, Chris Iden, Robert Heitman, and Anita Scott, and distributed by Sierra On-Line. It requires a 512K Apple IIgs.",
    "developer": "Doug & Ken MacNeill",
    "publisher": "Sierra"
  },
  {
    "id": "wozaday_Great_Western_Shootout_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Great Western Shootout",
    "nameEn": "Great Western Shootout",
    "year": "1989",
    "type": "game",
    "desc": "\"Great Western Shootout\" is a 1989 action game developed by Scott Patterson and Matt Crysdale, and distributed by Britannica Software. It requires a 512K Apple IIgs.",
    "developer": "Visual Concepts (Scott Patterson & Matt Crysdale)",
    "publisher": "Britannica / Fanfare"
  },
  {
    "id": "wozaday_Halls_of_Montezuma_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Halls of Montezuma",
    "nameEn": "Halls of Montezuma",
    "year": "1990",
    "type": "game",
    "desc": "\"Halls of Montezuma\" is a 1990 simulation game developed by Roger Keating, Ian Trout, Allan Bell, Sue Bell, and Steven Hart, and distributed by Strategic Studies Group. It requires a 1MB Apple IIgs ROM 01 or later.",
    "developer": "Roger Keating & Ian Trout",
    "publisher": "Strategic Studies Group"
  },
  {
    "id": "wozaday_Hover_Blade_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Hover Blade",
    "nameEn": "Hover Blade",
    "year": "1991",
    "type": "game",
    "desc": "\"Hover Blade\" is a 1991 action game developed by Shiraz Akmal and Eric Boden, and distributed by MCX. It requires a 1MB Apple IIgs ROM 01 or later.",
    "developer": "Shiraz Akmal & Eric Boden",
    "publisher": "MCX"
  },
  {
    "id": "wozaday_Keef_the_Thief_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Keef the Thief",
    "nameEn": "Keef the Thief",
    "year": "1989",
    "type": "game",
    "desc": "\"Keef the Thief\" is a 1989 roleplaying game developed by Andy Gavin and Jason Rubin, and distributed by Electronic Arts. It requires a 512K Apple IIgs.",
    "developer": "Naughty Dog (Andy Gavin & Jason Rubin)",
    "publisher": "Electronic Arts"
  },
  {
    "id": "wozaday_Mancala_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Mancala",
    "nameEn": "Mancala",
    "year": "1988",
    "type": "game",
    "desc": "\"Mancala\" is a 1988 board game developed by Jarek Olszewski, Maciej Markuszewski, Marcin Szostakowski, and Dorota Błaszczak, and distributed by Calfornia Dreams. It requires a 512K Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams"
  },
  {
    "id": "wozaday_Manhunter_New_York_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Manhunter: New York",
    "nameEn": "Manhunter: New York",
    "year": "1988",
    "type": "game",
    "desc": "\"Manhunter: New York\" is a 1987 adventure game developed by Dave Murry, Barry Murry, Dee Dee Murry, Jeff Stephenson, Chris Iden, Bob Heitman, Carlos Escobar, and Dr. Gary and Julie Stonedahl, and distributed by Sierra On-Line. It requires a 512K Apple IIgs.",
    "developer": "Dave, Barry and Dee Dee Murray",
    "publisher": "Sierra"
  },
  {
    "id": "wozaday_Marble_Madness_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Marble Madness",
    "nameEn": "Marble Madness",
    "year": "1988",
    "type": "game",
    "desc": "\"Marble Madness\" is a 1986 action game developed by Will Harvey and distributed by Electronic Arts. It requires a 512K Apple IIgs.",
    "developer": "Will Harvey",
    "publisher": "Electronic Arts"
  },
  {
    "id": "wozaday_Mazer_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Mazer II",
    "nameEn": "Mazer II",
    "year": "1992",
    "type": "game",
    "desc": "\"Mazer II\" is a 1992 action game developed by Mike Howard and distributed by Farfetch Software. It requires an Apple IIgs with at least 1.25MB RAM.",
    "developer": "Farfetch Software",
    "publisher": "Big Red Computer Club"
  },
  {
    "id": "wozaday_Mean_18_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Mean 18",
    "nameEn": "Mean 18",
    "year": "1987",
    "type": "game",
    "desc": "\"Mean 18\" is a 1987 sports game developed by Rex Bradford, George Karalias, and Mark Lesser, and distributed by Accolade. It requires a 512K Apple IIgs. This archive includes the three add-on disks that were available separately (Famous Courses Volume II, III, and IV).",
    "developer": "Mark Lesser & Micro Smiths",
    "publisher": "Accolade"
  },
  {
    "id": "wozaday_Mini_Putt_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Mini-Putt",
    "nameEn": "Mini-Putt",
    "year": "1988",
    "type": "game",
    "desc": "\"Mini-Putt\" is a 1988 sports game developed by Ross Salas and distributed by Accolade. It requires a 512K Apple IIgs.",
    "developer": "Ross Salas & Tanager Software Productions",
    "publisher": "Accolade"
  },
  {
    "id": "wozaday_Mixed_Up_Mother_Goose_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Mixed-Up Mother Goose",
    "nameEn": "Mixed-Up Mother Goose",
    "year": "1988",
    "type": "game",
    "desc": "\"Mixed-Up Mother Goose\" is a 1987 adventure game designed by Roberta Williams, with graphics by Jerry Moore, programming by David Slayback, music by Amenda-Lombardo, and distributed by Sierra On-Line. This is version 2.0A. It requires a 512K Apple IIgs.",
    "developer": "Roberta Williams",
    "publisher": "Sierra"
  },
  {
    "id": "wozaday_Panzer_Battles_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Panzer Battles",
    "nameEn": "Panzer Battles",
    "year": "1991",
    "type": "game",
    "desc": "\"Panzer Battles\" is a 1991 strategy game developed by Allan Bell, Sue Bell, and Steven Hart, and distributed by Strategic Studies Group. It requires a ROM1 or ROM3 Apple IIgs with at least 1.25MB RAM.",
    "developer": "Roger Keating, Danny Stevens & Ian Trout",
    "publisher": "Strategic Studies Group"
  },
  {
    "id": "wozaday_Police_Quest_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Police Quest",
    "nameEn": "Police Quest",
    "year": "1987",
    "type": "game",
    "desc": "\"Police Quest\" is a 1987 adventure game developed by Jim Walls, Greg Rowland, Al Lowe, Scott Murphy, Ken Williams, Mark Crowe, Jerry Moore, Margaret Lowe, Jeff Stephenson, Chris Iden, Bob Heitman, and Carlos Escobar, and distributed by Sierra On-Line. It requires a 512K Apple IIgs.",
    "developer": "Jim Walls",
    "publisher": "Sierra"
  },
  {
    "id": "wozaday_Qix_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Qix",
    "nameEn": "Qix",
    "year": "1990",
    "type": "game",
    "desc": "\"Qix\" is a 1990 action game developed by Ryan Ridges and John Lund, and distributed by Taito. It requires a 512K Apple IIgs.",
    "developer": "Ryan Ridges & John Lund",
    "publisher": "Taito America"
  },
  {
    "id": "wozaday_Questron_II_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Questron II",
    "nameEn": "Questron II",
    "year": "1988",
    "type": "game",
    "desc": "\"Questron II\" is a 1988 roleplaying game developed by Westwood Associates and distributed by Strategic Simulations, Inc. This is version 1.1. It requires a 512K Apple IIgs.",
    "developer": "Westwood",
    "publisher": "Strategic Simulations"
  },
  {
    "id": "wozaday_Revolution_76_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Revolution '76",
    "nameEn": "Revolution '76",
    "year": "1989",
    "type": "game",
    "desc": "\"Revolution '76\" is a 1988 strategy game developed by Edward Bever, Patricia Bever, Susan Barr, Sandra Lakin, David Craft, Andy Kanakares, and Ezra Sidran, and distributed by Britannica Software. This version is dated June 27, 1989 according to a printed stamp on the disk label. It requires a 1.25MB Apple IIgs ROM 01 or later.",
    "developer": "Edward and Patricia Bever",
    "publisher": "Britannica Software"
  },
  {
    "id": "wozaday_Roadwar_2000_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Roadwar 2000",
    "nameEn": "Roadwar 2000",
    "year": "1987",
    "type": "game",
    "desc": "\"Roadwar 2000\" is a 1987 simulation game developed by Westwood Associates and distributed by Strategic Simulations, Inc. It requires a 512K Apple IIgs.",
    "developer": "Westwood",
    "publisher": "Strategic Simulations"
  },
  {
    "id": "wozaday_Shadowgate_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Shadowgate",
    "nameEn": "Shadowgate",
    "year": "1988",
    "type": "game",
    "desc": "\"Shadowgate\" is a 1988 adventure game developed by Fred Allen, David Marsh, Karl Roelofs, Todd Squires, Steven Hays, Terry Schulenburg, Darin Adler, Jay Zipnick, Waldemar Horwat, Tod Zipnick, and David Feldman, and distributed by ICOM Simulations. It requires a 768K Apple IIgs.",
    "developer": "ICOM Simulations",
    "publisher": "Mindscape"
  },
  {
    "id": "wozaday_Silpheed_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Silpheed",
    "nameEn": "Silpheed",
    "year": "1989",
    "type": "game",
    "desc": "\"Silpheed\" is a 1987 action game developed by John Rettig, Stuart Goldstein, Mark Seibert, Satoshi Uesaki, Nobuyuki Ogawa, Akira Eye, Fumihito Kasatani, Nobuyuki Aoshima, Hiromi Ohba, Takeshi Miyaji, Osamu Harada, and Youichi Miyaji, and distributed by Sierra On-Line. It requires a 512K Apple IIgs.",
    "developer": "Game Arts",
    "publisher": "Sierra"
  },
  {
    "id": "wozaday_Solitaire_Royale_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Solitaire Royale",
    "nameEn": "Solitaire Royale",
    "year": "1990",
    "type": "game",
    "desc": "\"Solitaire Royale\" is a 1989 card game developed by Jake Hoelter, Jody Sather, Ilan \"The Zipper\" Zipkin, and Brad Fregger, and distributed by Spectrum Holobyte. This is version 1.0. It requires a 512K Apple IIgs.",
    "developer": "Jake Hoelter, Jody Sather & Brad Fregger",
    "publisher": "Spectrum Holobyte"
  },
  {
    "id": "wozaday_Space_Ace_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Space Ace",
    "nameEn": "Space Ace",
    "year": "1990",
    "type": "game",
    "desc": "\"Space Ace\" is a 1990 action game developed by David Foster, Simon Douglas, Jorge Freitas, Hugh MacLeod, Murray Foster, Laurie Williams, Adam Wolk, Michael Griffith, Peter Bayes, David Dimatteo, Sue McComb, and Joanne Ashdown, and distributed by ReadySoft. It requires a 1MB Apple IIgs.",
    "developer": "David Foster & Simon Douglas",
    "publisher": "Ready Soft"
  },
  {
    "id": "wozaday_Street_Sports_Soccer_IIgs",
    "emu": "apple2gsr1",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Street Sports Soccer",
    "nameEn": "Street Sports Soccer",
    "year": "1988",
    "type": "game",
    "desc": "\"Street Sports Soccer\" is a 1988 sports game developed by Designer Software and distributed by Epyx. It requires a 512K Apple IIgs ROM 00 or ROM 01.",
    "developer": "Designer Software",
    "publisher": "Epyx"
  },
  {
    "id": "wozaday_Sub_Battle_Simulator_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Sub Battle Simulator",
    "nameEn": "Sub Battle Simulator",
    "year": "1987",
    "type": "game",
    "desc": "\"Sub Battle Simulator\" is a 1987 simulation game developed by Rob Brannon, Kelly Fergason, and Steve Snyder, and distributed by Epyx. It requires a 768K Apple IIgs.",
    "developer": "Rob Brannon & Kelly Fergason",
    "publisher": "Epyx"
  },
  {
    "id": "wozaday_Superstar_Ice_Hockey_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Superstar Ice Hockey",
    "nameEn": "Superstar Ice Hockey",
    "year": "1988",
    "type": "game",
    "desc": "\"Superstar Ice Hockey\" is a 1988 sports game developed by Ed Ringler, Andrew Caldwell, Clayton Wishoff, Simon Ffinch, Ed Ringler Sr., and Chris Oke, and distributed by Mindscape. It requires a 512K Apple IIgs.",
    "developer": "DesignStar Consultants (Andrew Caldwell)",
    "publisher": "Mindscape"
  },
  {
    "id": "wozaday_Tarot_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Tarot",
    "nameEn": "Tarot",
    "year": "1990",
    "type": "game",
    "desc": "\"Tarot\" is a 1990 French language card game developed by François Uhrich and Jean-François Sauvage, and distributed by Toolbox. It requires a 1MB Apple IIgs ROM 01 or later.",
    "developer": "François Uhrich & Jean-François Sauvage",
    "publisher": "Toolbox"
  },
  {
    "id": "wozaday_Task_Force_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Task Force",
    "nameEn": "Task Force",
    "year": "1990",
    "type": "game",
    "desc": "\"Task Force\" is a 1990 action game developed by Scott L. Patterson, Matthew Crysdale, and Gregory A. Thomas, and distributed by Britannica Software. It requires a 1MB Apple IIgs.",
    "developer": "Visual Concepts (Scott Patterson & Matt Crysdale)",
    "publisher": "Britannica / Fanfare"
  },
  {
    "id": "wozaday_Tass_Times_in_Tonetown_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Tass Times in Tonetown",
    "nameEn": "Tass Times in Tonetown",
    "year": "1986",
    "type": "game",
    "desc": "\"Tass Times in Tonetown\" is a 1986 adventure game developed by Rebecca Heineman, Todd Camasta, Russell Lieblich, Brian Fargo, and Steve Nielsen, and distributed by Activision. It requires a 256K Apple IIgs.",
    "developer": "Rebecca Heineman (Interplay Productions & Brainwave Creations)",
    "publisher": "Activision"
  },
  {
    "id": "wozaday_Tetris_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Tetris",
    "nameEn": "Tetris",
    "year": "1988",
    "type": "game",
    "desc": "\"Tetris\" is a 1988 action game developed by Roland Gustafsson, Sean B. Barger, Dan Geisler, Daniel L. Guerra, Jody Sather, Ed Bogas, Neil Cormia, Ty Roberts, and Gary Clayton, and distributed by Spectrum HoloByte. It requires a 512K Apple IIgs.",
    "developer": "Roland Gustafsson, Sean Barger & Dan Geisler",
    "publisher": "Spectrum Holobyte"
  },
  {
    "id": "wozaday_Tunnels_of_Armageddon_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Tunnels of Armageddon",
    "nameEn": "Tunnels of Armageddon",
    "year": "1990",
    "type": "game",
    "desc": "\"Tunnels of Armageddon\" is a 1989 action game developed by Jarek Achinger, Adam Skorupiński, Mirek Zabłocki, Krzysiek Koziarski, Zbych Dąbrowski, Dorota Błaszczak, Marcin Grzegorzewski, Dick Vohlers, Tomek Meuś, and distributed by California Dreams. This is version 1.0. It requires a 512K Apple IIgs.",
    "developer": "Logical Design Works",
    "publisher": "California Dreams"
  },
  {
    "id": "wozaday_War_in_Middle_Earth_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "file2": "00playable2.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "War in Middle Earth",
    "nameEn": "War in Middle Earth",
    "year": "1989",
    "type": "game",
    "desc": "\"War in Middle Earth\" is a 1989 adventure game developed by Ron Harris, Robert Clardy, Alan B. Clark, Graeme Devine, Mike Branham, Lloyd Ollmann, Jr., John Conley, Jim McBride, Michael Park, David Schroeder, Michael Ormsby, Mike Christy, Ann Dickens Clardy, Marcus Streets, Mark Riley, and Mike Singleton, and distributed by Melbourne House. It requires a 768K Apple IIgs ROM01 or later.",
    "developer": "Synergistic Software",
    "publisher": "Melbourne House"
  },
  {
    "id": "wozaday_Winter_Games_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "Winter Games",
    "nameEn": "Winter Games",
    "year": "1987",
    "type": "game",
    "desc": "\"Winter Games\" is a 1987 sports game developed by Westwood Studios and distributed by Epyx. It requires a 512K Apple IIgs.",
    "developer": "Westwood & IT",
    "publisher": "Epyx"
  },
  {
    "id": "wozaday_World_Tour_Golf_IIgs",
    "emu": "apple2gs",
    "file": "00playable.woz",
    "screenshot": "00playable_screenshot.png",
    "name": "World Tour Golf",
    "nameEn": "World Tour Golf",
    "year": "1987",
    "type": "game",
    "desc": "\"World Tour Golf\" is a 1987 sports game developed by Evan & Nicky Robinson and Paul Reiche III, ported to the Apple IIgs by John Selhorst, and distributed by Electronic Arts. It requires a 512K Apple IIgs.",
    "developer": "John Selhorst & Tanager Software Productions",
    "publisher": "Electronic Arts"
  }
,
  // === 教育軟體 (精選) ===
  {
    id: 'wozaday_Charlie_Browns_ABCs_IIgs',
    emu: 'apple2gs',
    file: '00playable.woz',
    file2: '00playable2.woz',
    screenshot: '00playable_screenshot.png',
    name: '查理布朗字母學習',
    nameEn: "Charlie Brown's ABCs",
    year: '1990',
    type: 'edu',
    desc: '以史努比漫畫為主題的兒童教育軟體。透過有趣的方式教導兒童學習英文字母，配合可愛的圖形和互動練習。',
    developer: 'Susan Mahoney & Associates',
    publisher: 'American School Publishers'
  },
  {
    id: 'wozaday_The_New_Talking_Stickybear_Alphabet_IIgs',
    emu: 'apple2gs',
    file: '00playable.woz',
    screenshot: '00playable_screenshot.png',
    name: '會說話的字母熊',
    nameEn: 'Talking Stickybear Alphabet',
    year: '1988',
    type: 'edu',
    desc: '互動式字母學習軟體。Stickybear 熱陪伴兒童學習 26 個英文字母。每個字母都有語音發音、相關單字和互動遊戲。',
    developer: 'Optimum Resource',
    publisher: 'Optimum Resource'
  },

  // === 工具軟體 (精選) ===
  {
    id: 'wozaday_List_Plus_IIgs',
    emu: 'apple2gs',
    file: '00playable.woz',
    screenshot: '00playable_screenshot.png',
    name: 'List Plus',
    nameEn: 'List Plus',
    year: '1989',
    type: 'tool',
    desc: 'Beagle Bros 出品的程式開發工具。用於編輯、列印和分析 Applesoft BASIC 程式碼。提供語法高亮、縮排格式化、搜尋替換等功能。',
    developer: 'Beagle Bros',
    publisher: 'Beagle Bros'
  },

  // === 特別收藏 ===
  {
    id: 'TotalReplay',
    emu: 'apple2gs',
    file: '00playable.2meg',
    screenshot: '00playable_screenshot.png',
    name: 'Total Replay (100款合集)',
    nameEn: 'Total Replay',
    year: '2024',
    type: 'special',
    desc: '包含 100 款精選 Apple II 遊戲的終極合集。由社群精心整理,涵蓋動作、冒險、益智等各類型經典遊戲。這是體驗 Apple II 黃金時代最完整的收藏。',
    developer: '社群整理',
    publisher: '4am'
  },
  {
    id: 'PitchDark',
    emu: 'apple2gs',
    file: '00playable.hdv',
    screenshot: '00playable_screenshot.png',
    name: 'Pitch Dark (漆黑)',
    nameEn: 'Pitch Dark',
    year: '2023',
    type: 'special',
    desc: '現代復刻版的 Infocom 風格文字冒險遊戲。完全以文字呈現的互動小說,玩家需要透過閱讀描述和輸入指令來探索黑暗的世界。',
    developer: '社群製作',
    publisher: 'Interactive Fiction'
  }

];
